
import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const translations = {
  en: {
    // Theme
    'theme_light': 'Light Mode',
    'theme_dark': 'Dark Mode',

    // Login & Dashboard
    'enter_btn': 'Enter System',
    'register_btn': 'Create Account',
    'no_account': "Don't have an account?",
    'already_have_account': 'Already have an account?',
    'register_title': 'Create FTTx Planner Account',
    'back_to_login': 'Back to Login',
    'registration_success': 'Account created! You can now log in.',
    'registration_failed': 'Registration failed. Username might be taken.',
    'login_title': 'FTTx Planner',
    'login_subtitle': 'Enter your credentials',
    'login_email_placeholder': 'Email',
    'login_password_placeholder': 'Password',
    'login_button_loading': 'Logging in...',
    'login_button': 'Login',
    'login_create_account': 'Create new account',
    'login_feature_label': 'Feature',
    'login_feature_title': 'Fusion Editor',
    'back_to_home': 'Back to Home',
    'register_page_title': 'Create FTTx Planner Account',
    'register_subtitle': 'Join FTTx Master Planner',
    'register_company_placeholder': 'Company Name (ISP)',
    'register_password_placeholder': 'Password',
    'register_confirm_password_placeholder': 'Confirm Password',
    'register_button': 'Register Account',
    'register_already_have_account': 'Already have an account? Login',
    'register_error_empty': 'Please fill all fields.',
    'register_error_match': 'Passwords do not match.',
    'welcome': 'Welcome, {name}',
    'logout': 'Logout',
    'my_projects': 'My Projects',
    'create_new_project_btn': 'Create New Project',
    'no_projects': 'No projects found. Create your first one!',
    'last_modified': 'Last modified: {date}',
    'open_project': 'Open Project',
    'exit_project': 'Exit to Dashboard',
    'delete_project_confirm': 'Are you sure you want to delete project "{name}"?',
    'project_updated': 'Project updated successfully!',
    'toast_project_deleted': 'Project deleted successfully!',
    'error_project_update': 'Failed to update project.',
    'error_project_delete': 'Failed to delete project.',

    // App / Sidebar
    'app_title': 'FTTH Planner',
    'active_project': 'Active Project',
    'tools': 'Tools',
    'settings': 'Settings',
    'system_settings': 'Settings',
    'view_options': 'View Options',
    'toggle_labels': 'Labels',
    'sidebar_collapse': 'Collapse Menu',
    'sidebar_expand': 'Expand Menu',
    'menu': 'Menu',
    'home': 'Home',
    'mode_view': 'Selection / Nav',
    'mode_move': 'Move Elements',
    'mode_otdr': 'OTDR Trace',
    'mode_add_cto': 'Place CTO',
    'mode_add_pop': 'Place POP',
    'mode_draw_cable': 'Draw Cable',
    'mode_connect_cable': 'Connect Cable',
    'select_project_placeholder': 'Select Project...',
    'ai_audit': 'AI Network Audit',
    'analyzing': 'Analyzing...',
    'tooltip_view': 'Navigation Mode: Click markers or cables to select/edit.',
    'tooltip_move': 'Move Mode: Drag CTOs or POPs to adjust position.',
    'tooltip_otdr': 'OTDR Mode: Click a cable to locate a distance/event.',
    'tooltip_add_cto': 'Placement Mode: Click on map to add CTO.',
    'tooltip_add_pop': 'Placement Mode: Click on map to add a Central Office (POP).',
    'tooltip_add_pole': 'Placement Mode: Click on map to add a Pole.',
    'tooltip_draw_cable': 'Drawing: Click anywhere to draw cable. Click markers to snap.',
    'tooltip_draw_cable_start': 'Drawing: Click map or Node to start cable.',
    'tooltip_connect': 'Connection Mode: Click cable line to add SPLIT point. Drag point to Node to connect.',
    'ai_report_title': 'AI Engineer Report',
    'deployment_progress': 'Deployment Progress',
    'search_placeholder': 'Search CTO, POP or Coordinates...',
    'search_no_results': 'No results found',

    // New Sidebar Keys
    'sidebar_operation': 'Operation',
    'sidebar_select': 'Select',
    'sidebar_move': 'Move',
    'sidebar_design': 'Network Design',
    'sidebar_pole': 'Pole',
    'sidebar_add_cto': 'New CTO',
    'sidebar_add_pop': 'New POP',
    'sidebar_draw_cable': 'Draw Cable',
    'sidebar_draw_cable_desc': 'Click for multiple points',
    'sidebar_connect_cable': 'Connect/Edit Cables',
    'sidebar_connect_cable_desc': 'Adjust connections & geometry',
    'registrations': 'Registrations',
    'manage_networks_desc': 'Manage and organize your FTTx networks.',
    'cables': 'Cables',
    'search_generic': 'Search...',
    'reg_poste': 'Pole',
    'reg_caixa': 'Box',
    'reg_cabo': 'Cable',
    'reg_splitter': 'Splitter',
    'reg_fusao': 'Fusion',
    'backup': 'Backup',
    'upgrade_now': 'Upgrade Now',
    'manage_subscription': 'Manage Subscription',
    'trial': 'Trial',
    'expires': 'Expires',
    'days': 'days',
    'registration_title': 'Registration: {name}',
    'registration_placeholder_desc': '{name} registration module under development.',
    'new_fusion': 'New Fusion',
    'edit_fusion': 'Edit Fusion',
    'fusion_catalog_desc': 'Manage fusion types and attenuation.',
    'module_under_development': 'This module is currently under development.',
    'splitter_catalog_desc': 'Manage your splitter catalog types.',
    'add_splitter': 'Add Splitter',
    'confirm_delete': 'Are you sure?',
    'search_splitters': 'Search splitters...',
    'edit_splitter': 'Edit Splitter',
    'new_splitter': 'New Splitter',
    'splitter_name': 'Name',
    'ctx_remove_cable': 'Remove Cable from Box',
    'ctx_edit_cable': 'Edit Cable',
    'ctx_next_box': 'Go to Next Box',
    'action_flip': 'Flip',
    'action_rotate': 'Rotate',
    'ctx_details': 'Details',
    'toast_select_next_box': 'Select the target box to navigate to',
    'error_cable_fully_connected': 'Cable is already fully connected',
    'splitter_type': 'Type',
    'splitter_mode': 'Mode',
    'inputs': 'Inputs',
    'outputs': 'Outputs',
    'attenuation': 'Attenuation',
    'attenuation_db': 'Attenuation (dB)',
    'description': 'Description',

    'loading': 'Loading...',
    'loading_diagram': 'Loading diagram...',
    'error_saving_splitter': 'Error saving splitter',
    'attenuation_help': 'For Unbalanced, describe the split ratio attenuation.',
    'attenuation_port1': 'Attenuation Port 1 (dB)',
    'attenuation_port2': 'Attenuation Port 2 (dB)',
    'splitter_ports': 'Ports',
    'splitter_in': 'In',
    'splitter_out': 'Out',
    'splitter_mode_balanced': 'Balanced',
    'splitter_mode_unbalanced': 'Unbalanced',

    // OLT Catalog
    'reg_olt': 'OLT',
    'olt_catalog_desc': 'Manage your OLT models and output power.',
    'search_olts': 'Search OLTs...',
    'no_olts_found': 'No OLTs found.',
    'olt_name': 'Model Name',
    'output_power': 'Output Power (dBm)',
    'olt_slots': 'Slots',
    'ports_per_slot': 'Ports/Slot',
    'edit_olt': 'Edit OLT',
    'new_olt': 'New OLT',
    'add_olt': 'Add OLT',
    'error_saving_olt': 'Error saving OLT',

    // Toasts
    'toast_imported': 'Imported {ctos} CTOs and {cables} Cables',
    'toast_cto_added': 'CTO added successfully',
    'toast_pop_added': 'POP added successfully',
    'toast_cto_splicing_saved': 'CTO Splicing saved',
    'toast_pop_saved': 'POP configuration saved',
    'toast_cto_deleted': 'CTO deleted successfully',
    'toast_pole_deleted': 'Pole deleted successfully',
    'toast_pole_added': 'Pole added successfully',
    'toast_pop_deleted': 'POP deleted',
    'toast_cable_updated': 'Cable updated',
    'toast_cable_deleted': 'Cable deleted successfully',
    'toast_cable_created': 'Cable created successfully',
    'toast_cable_connected_start': 'Cable start connected to {name}',
    'toast_cable_connected_end': 'Cable end connected to {name}',
    'toast_cable_anchored_pole': 'Cable anchored to pole {name}',
    'toast_cable_split': 'Cable split (Sangria) and connected to {name}',
    'import_error': 'Failed to import file. See console for details.',
    'import_no_geo': 'No compatible geometry (Points or Lines) found in this file.',
    'toast_mode_move_node': 'Move mode activated',
    'error_cto_duplicate_cable': 'This cable is already connected to this CTO.',
    'toast_auto_snap_success': 'Auto-connected/Split {count} locations within {distance}m.',
    'toast_poles_imported': '{count} poles imported successfully!',
    'toast_poles_import_error': 'Error importing poles.',
    'error_cable_endpoint_missing': 'Loose cable at other end',
    'error_target_not_found': 'Target not found',
    'toast_select_next_cable': 'Select another cable to connect',
    'toast_cable_disconnected': 'Cable disconnected',

    // OTDR Messages & Errors
    'otdr_title': 'OTDR Calculator',
    'otdr_distance_lbl': 'Distance (Meters)',
    'otdr_direction': 'Direction',
    'otdr_from_start': 'From Start/Node A',
    'otdr_from_end': 'From End/Node B',
    'otdr_locate': 'Locate Event',
    'otdr_result': 'Event Location',
    'otdr_error_length': 'Distance exceeds cable length ({length}m)',
    'otdr_trace_start_error': 'OTDR Trace: Please start from a cable fiber port.',
    'otdr_cable_not_found': 'OTDR Error: Cable not found.',
    'otdr_conn_mismatch': 'OTDR Error: Cable connectivity mismatch.',
    'otdr_end_open': 'OTDR: End of fiber reached (Open End).',
    'otdr_next_node_error': 'OTDR Error: Next node not found.',
    'otdr_fiber_end_node': 'OTDR: Fiber ends at {node} (Not Spliced).',
    'otdr_event_equipment': 'OTDR: Event at {node} (Equipment Connection).',
    'otdr_max_depth': 'OTDR: Max trace depth reached.',
    'otdr_success_cable': 'Located in cable {name}',
    'otdr_inside_cto': 'Inside CTO {name}',
    'otdr_trace_msg': 'Trace from selected fiber',
    'otdr_instruction_banner': 'Click a fiber port to measure distance.',
    'otdr_event_tooltip': 'OTDR Event',
    'otdr_traversing_pole': 'Traversing pole {name}...',

    // Common
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',

    'name': 'Name',
    'status': 'Status',
    'type': 'Type',
    'copy_coordinates': 'Copy Coordinates',
    'open_google_maps': 'Open in Google Maps',
    'coordinates': 'Coordinates',
    'pinned_location': 'Save as',
    'viability_status': 'Viability Status',
    'viability_available': 'Service Available',
    'viability_unavailable': 'No Service',
    'distance_nearest': 'Dist. Nearest: {dist}m',
    'convert_to_cto': 'Convert to CTO',
    'convert_to_pole': 'Convert to Pole',
    'remove_pin': 'Remove Pin',
    'manage_splicing': 'Manage Splicing',
    'manage_pop': 'Manage Rack & Patching',
    'unsaved_changes': 'Unsaved Changes',
    'unsaved_changes_msg': 'You have unsaved changes. Do you want to save them before closing?',
    'discard': 'Discard',
    'save_and_close': 'Save & Close',
    'save_or_done': 'Save / Exit',
    'clear_connections_confirm': 'Are you sure you want to clear ALL connections? This cannot be undone.',
    'clear_all': 'Clear All',
    'confirm_delete_equip_msg': 'Are you sure you want to delete {name}?',
    'delete_warning_msg': 'Warning: All connections associated with this {type} will be removed permanently.',
    'changes_saved': 'Changes saved successfully',
    'position_saved': 'Position saved successfully!',
    'save_position': 'Save Position',
    'moving_node': 'Moving Element...',
    'editing_cable': 'Editing Cable...',
    'connecting_cable': 'Connecting Cables...',
    'finish': 'Finish',
    'finish_cable': 'Finish Cable',
    'connection_cancelled': 'Connection Cancelled',
    'meters': 'meters',
    'saved': 'Saved',
    'done': 'Done',

    // Statuses
    'status_PLANNED': 'In Project',
    'status_ANALYSING': 'Analysing',
    'status_LICENSED': 'Licensed',
    'pole_properties': 'Pole Properties',
    'selection_pole_type': 'Pole Type',
    'pole_height_placeholder': 'Ex: 10',
    'confirm_delete_pole_msg': 'Are you sure you want to delete this pole?',

    // CTO/POP Details
    'edit_cto': 'Edit CTO',
    'edit_pop': 'Edit POP',
    'cto_info': 'CTO Information',
    'pop_info': 'POP Information',

    'connections': 'Connections',
    'spliced': 'Spliced',
    'patched': 'Patched',
    'splitters': 'Splitters',
    'equipment': 'Equipment',
    'backbone_cables': 'Backbone Cables',
    'confirm_delete_cto_msg': 'Confirm deletion of {name}? All connected cables will be removed.',
    'confirm_delete_pop_msg': 'Confirm deletion of POP {name}? This will remove all racks, equipment, and connected cables.',
    'delete_cto_btn': 'Delete CTO',
    'delete_pop_btn': 'Delete POP',

    // Cable Editor
    'edit_cable': 'Edit Cable',
    'cable_name': 'Cable Name',
    'fiber_count': 'Fiber Count',
    'loose_tubes': 'Loose Tubes',
    'tube': 'Tube',
    'estimated_length': 'Estimated Length',
    'map_color': 'Map Color',
    'disabled': 'Disabled',
    'save_changes': 'Save Changes',
    'confirm_delete_cable_msg': 'Confirm deletion of {name}? This will remove associated fusion splices.',
    'color_standard': 'Color Standard',
    'standard_abnt': 'ABNT (Brazil)',
    'standard_eia': 'EIA-598-A (Intl)',

    // Project Manager / Create Modal
    'project_manager': 'Project Manager',
    'create_project': 'Create Project',
    'new_project_placeholder': 'Project Name (e.g. Center Expansion)',
    'import_kmz_title': 'Import KMZ/KML to Current Project',
    'import_kmz_desc': 'Clique to upload .kmz or .kml file',
    'processing': 'Processing...',
    'your_projects': 'Your Projects',
    'load_project': 'Load',
    'delete_last_project_error': 'Cannot delete the last project.',
    'items_count': 'Items: {ctos} CTOs, {cables} Cabos',
    'search_location': 'Initial Location',
    'search_location_placeholder': 'Search city or address...',
    'searching_location': 'Searching...',
    'no_location_results': 'No location found',

    'create_project_modal_title': 'Create New Project',
    'edit_project': 'Edit Project',
    'map_instruction': 'Drag the map or click to set the project center.',
    'confirm_create': 'Create Project',
    'snap_distance_lbl': 'Auto-Connect Distance (meters)',
    'snap_distance_help': 'Maximum distance for a cable to automatically snap to a box (CTO/POP) when dragging.',

    // CTO Internal Editor
    'splicing_title': '{name}',
    'dio_splicing_title': 'DIO Splicing: {name}',
    'splicing_help': 'Mouse Wheel to Zoom. Drag Background to Pan. Double-click points to remove.',

    'add_fusion': 'Fusion',
    'auto_splice': 'Auto Pass-Through',
    'reset_connections': 'Reset Connections',
    'drop_to_connect': 'Drop on a port to connect, or background to disconnect.',
    'moving_point': 'Moving control point...',
    'panning': 'Panning',
    'general_help': 'Drag ports to connect. Click lines to add points. Double-click points to remove. Double-click names to rename.',
    'rename_fusion': 'Rename Fusion Point:',
    'export_pdf': 'Export PDF',
    'generating_pdf': 'Generating...',
    'tool_vfl': 'VFL (Visual Fault Locator)',
    'vfl_active_msg': 'VFL Active: Click any port to inject light.',
    'vfl_active_status': 'VFL Active',
    'vfl_source_label': 'Source: {name}',
    'turn_off': 'Turn Off',
    'source_cable': 'Source Cable',
    'target_cable': 'Target Cable',
    'perform_splice': 'Fuse All Fibers',
    'splice_success': 'Successfully fused {count} fibers.',
    'smart_align': 'Smart Align',
    'select_fusion_type': 'Select Fusion Type',
    'fusion_tool_active': 'Fusion Mode: Click to add fusion point',

    // DIO Editor Strings
    'link_cables': 'Link Cables',
    'no_available_fusions': 'No fusion types registered',
    'linked_pole': 'Linked Pole',
    'link_to_nearest_pole': 'Link to nearest pole',
    'linked_cables': 'Linked Cables',
    'link_to_nearest_cables': 'Link nearest cables',
    'unlinked': 'Unlinked',
    'link_cables_help': 'You can link cables to this DIO using the button above.',
    'connect_fiber_tray': 'Connect Fiber to DIO Tray',
    'connected_to_port': 'Currently connected to Port {port}',
    'select_tray_port_help': 'Select a tray port below to splice this fiber.',
    'green_light_help': 'Green lights indicate active OLT signal flowing to the cable.',
    'select_target_port_dio': 'Select a Target Port on {name}',
    'currently_connected': 'Currently Connected',
    'port_occupied_splice': 'Port occupied by another splice',
    'port_has_patch_cord': 'Port has patch cord (Splice allowed)',
    'port_available': 'Available',
    'linked_to_dio': 'Linked to {name}',
    'legend_active_signal': 'Active Signal',
    'legend_vfl_source': 'VFL Source',
    'unit_meters': 'METERS',
    'click_to_manage': 'Click to Manage',
    'click_to_connect': 'Click to Connect',
    'splice_trays': 'Splice Trays',

    // New Translations for Trays
    'tray': 'Tray',
    'trays': 'Trays',

    // Box Catalog
    'box_catalog': 'Box Catalog',
    'box_catalog_desc': 'Manage available box models (CTO/CEO).',
    'box_model': 'Box Model',
    'select_box_model': 'Select Model...',
    'reserve_loop_length': 'Tech. Reserve',
    'reserve': 'Reserve',
    'brand': 'Brand',
    'model': 'Model',
    'ident_color': 'Color',
    'type_cto_termination': 'CTO (Termination)',
    'type_ceo_splice': 'CEO (Splice)',
    'edit_box': 'Edit Box',
    'new_box': 'New Box',
    'search_placeholder_box': 'Search by name, brand or model...',
    'add_new': 'Add New',
    'details_placeholder': 'Additional details...',
    'bm_cancel': 'Cancel',

    // Pole Catalog
    'pole_catalog': 'Pole Catalog',
    'pole_catalog_desc': 'Manage the available pole models.',
    'pole_height': 'Height (m)',
    'pole_strength': 'Strength (daN)',
    'pole_shape': 'Shape',
    'shape_circular': 'Circular',
    'shape_duplot': 'Double T',
    'shape_square': 'Square',
    'edit_pole': 'Edit Pole',
    'new_pole': 'New Pole',
    'error_save': 'Failed to save',


    // POP Editor
    'pop_editor_title': 'POP Management: {name}',
    'add_dio': 'Add DIO',
    'olt_ports': 'PON Ports',
    'dio_ports': 'Ports',
    'rack_view': 'Rack View',

    // Map Layers
    'map_street': 'Street',
    'map_satellite': 'Satellite',
    'layer_ctos': 'CTOs',
    'layer_pops': 'POPs',

    // Users Module
    'users': 'Users',
    'users_manage_desc': 'Manage team members and their roles.',
    'add_user': 'Add User',
    'username': 'Username',
    'role': 'Role',
    'created_at': 'Created At',
    'actions': 'Actions',
    'no_users_found': 'No users found.',
    'role_member': 'Member',
    'role_admin': 'Admin',
    'role_owner': 'Owner',
    'password': 'Password',
    'edit_user': 'Edit User',
    'update': 'Update',
    'confirm_delete_user_msg': 'Are you sure you want to delete user {username}?',
    'create': 'Create',

    // User Management Errors
    'error_username_taken': 'Username is already taken.',
    'error_password_length': 'Password must be at least 6 characters long.',
    'error_cannot_delete_self': 'You cannot delete your own account.',
    'error_generic': 'An unexpected error occurred.',
    'error_create_user': 'Failed to create user.',
    'error_delete_user': 'Failed to delete user.',

    // --- LANDING PAGE ---
    'landing_features': 'Features',
    'landing_performance': 'Performance',
    'landing_how_it_works': 'How it Works',
    'landing_login': 'Log in',
    'landing_get_started': 'Get Started',
    'landing_hero_badge': 'New Generation Platform',
    'landing_hero_title_1': 'The Ultimate',
    'landing_hero_title_2': 'FTTH Network',
    'landing_hero_title_3': 'Management Platform',
    'landing_hero_desc': 'Design, document, and manage your fiber network with high-performance interactive maps. Built for ISPs who demand precision and scalability.',
    'landing_start_trial': 'Start Free Trial',
    'landing_live_demo': 'See Live Demo',
    'landing_map_engine': 'Map Engine',
    'landing_leaflet': 'Leaflet Powered',

    'landing_problem_title': 'Stop Managing Networks with',
    'landing_problem_highlight': 'Spreadsheets',
    'landing_problem_desc': 'Traditional methods like Google Earth + Excel are prone to errors, lack real-time updates, and become unmanageable as your network grows. You need a system that understands fiber optics, signal loss, and topology.',
    'landing_problem_1': 'No visibility into available ports',
    'landing_problem_2': 'Manual documentation is always outdated',
    'landing_problem_3': 'Hard to track signal loss and fusion points',
    'landing_problem_4': 'Team collaboration is a nightmare',
    'landing_error_connection': 'Error: Connection limit exceeded',

    'landing_features_title': 'Everything You Need to Scale',
    'landing_features_desc': 'From planning to deployment, our tool covers every aspect of your ISP operation.',
    'landing_feat_maps': 'Interactive Maps',
    'landing_feat_maps_desc': 'Visualize your entire network on high-performance maps. Zoom, pan, and edit with precision.',
    'landing_feat_cable': 'Cable & Fusion Management',
    'landing_feat_cable_desc': 'Track every fiber strand, fusion splice, and splitter connection. Auto-calculate signal loss.',
    'landing_feat_team': 'Multi-Tenant & Teams',
    'landing_feat_team_desc': 'Manage multiple projects and assign role-based access control to your engineering team.',
    'landing_feat_snap': 'Auto-Snap & Design Tools',
    'landing_feat_snap_desc': 'Smart drawing tools that snap to existing infrastructure, speeding up your design process by 50%.',
    'landing_feat_bom': 'Inventory & Reports',
    'landing_feat_bom_desc': 'Generate BOM (Bill of Materials) automatically. Know exactly how much cable you need.',
    'landing_feat_import': 'Import/Export',
    'landing_feat_import_desc': 'Seamlessly import KMZ/KML files from Google Earth and export your projects for field teams.',

    'landing_perf_badge': 'Ultra Performance',
    'landing_perf_title': 'Built for Millions of Elements',
    'landing_perf_desc': "Don't let lag slow you down. Our engine is optimized for browsing massive networks with zero latency. Handle city-wide deployments with thousands of CTOs and POPs seamlessly.",
    'landing_stat_elements': 'Elements rendered',
    'landing_stat_scroll': 'Smooth scroll',
    'landing_stat_search': 'Search time',
    'landing_stat_uptime': 'Uptime',
    'landing_graph_engine': 'Rendering Engine',
    'landing_graph_active': 'Active',
    'landing_graph_load': 'System Load: 5%',

    'landing_sec_title': 'Enterprise-Grade Security',
    'landing_sec_desc': 'Your network data is your most valuable asset. We treat it with the protection it deserves.',
    'landing_sec_1': 'End-to-End Encryption',
    'landing_sec_2': 'Daily Backups',
    'landing_sec_3': 'Role-Based Access',
    'landing_sec_4': 'Audit Logs',
    'landing_sec_5': '99.9% SLA',

    'landing_steps_title': 'Start in 3 Simple Steps',
    'landing_step_1_title': 'Create Workspace',
    'landing_step_1_desc': 'Sign up and create your first project area in seconds.',
    'landing_step_2_title': 'Design or Import',
    'landing_step_2_desc': 'Draw your network or import existing KMZ files instantly.',
    'landing_step_3_title': 'Manage & Scale',
    'landing_step_3_desc': 'Invite your team and start managing operations.',

    'landing_cta_title': 'Ready to modernize your ISP?',
    'landing_cta_desc': 'Join hundreds of network engineers who trust FTTH Master for their daily operations.',
    'landing_cta_btn': 'Get Started for Free',

    'landing_footer_desc': 'The professional standard for FTTH network design and management.',
    'landing_footer_product': 'Product',
    'landing_footer_company': 'Company',
    'landing_footer_legal': 'Legal',
    'landing_footer_rights': '© 2024 FTTH Master. All rights reserved.',

    // Pricing
    'pricing_title': 'Simple, Transparent Pricing',
    'pricing_desc': 'Choose the perfect plan for your ISP growth stage. No hidden fees.',
    'plan_free': 'Free',
    'plan_basic': 'Basic',
    'plan_inter': 'Intermediate',
    'plan_unlimited': 'Unlimited',
    'price_free': 'Free',
    'month': '/month',
    'feature_projects': '{count} Projects',
    'feature_users': '{count} Users',
    'feature_ctos': '{count} CTOs',
    'feature_pops': '{count} POPs',
    'feature_unlimited': 'Unlimited',
    'plan_cta': 'Get Started',
    'most_popular': 'Most Popular',
    'feature_1_project': '1 Project',
    'feature_1_user': '1 User',
    'feature_basic_maps': 'Basic Maps',
    'feature_5_projects': '5 Projects',
    'feature_3_users': '3 Users',
    'feature_email_support': 'Email Support',
    'feature_unlimited_all': 'Unlimited Everything',
    'feature_priority_support': 'Priority Support',
    'feature_auto_backup': 'Automatic Backup',
    'feature_projects_unlimited': 'Unlimited Projects',
    'feature_users_unlimited': 'Unlimited Users',
    'feature_ctos_unlimited': 'Unlimited CTOs',

    // Backup
    'backup_title': 'Backup Manager',
    'backup_desc': 'Manage your system backups. Daily backups are performed automatically at 02:00 AM.',
    'create_backup': 'Create Backup',
    'backup_filename': 'Filename',
    'backup_date': 'Date',
    'backup_size': 'Size',
    'download': 'Download',
    'confirm_delete_backup': 'Are you sure you want to delete this backup?',
    'backup_success': 'Backup created successfully',
    'backup_created_at': 'Created At',
    'backup_manual': 'Manual',

    'backup_auto': 'Automatic',
    'no_backups': 'No backups found.',
    'restore': 'Restore',
    'upload_restore': 'Upload & Restore',
    'restore_confirm': 'WARNING: This will delete ALL current network data (CTOs, Cables, POPs, Projects) and replace it with the backup. This cannot be undone. Are you sure?',
    'restore_success': 'System restored successfully. Reloading...',
    'pon': 'PON',
    'slot': 'Slot',
    'properties': 'Properties',
  },
  pt: {
    // Theme
    'theme_light': 'Modo Claro',
    'theme_dark': 'Modo Escuro',

    // --- LANDING PAGE ---
    'landing_features': 'Recursos',
    'landing_performance': 'Performance',
    'landing_pricing': 'Planos',
    'landing_how_it_works': 'Como Funciona',
    'landing_login': 'Entrar',
    'landing_get_started': 'Começar',
    'landing_hero_badge': 'Nova Geração',
    'landing_hero_title_1': 'A Plataforma Definitiva',
    'landing_hero_title_2': 'de Rede FTTH',
    'landing_hero_title_3': 'Gestão e Projetos',
    'landing_hero_desc': 'Projete, documente e gerencie sua rede de fibra com mapas interativos de alta performance. Feito para provedores que exigem precisão e escala.',
    'landing_start_trial': 'Teste Grátis',
    'landing_live_demo': 'Ver Demo',
    'landing_map_engine': 'Motor de Mapa',
    'landing_leaflet': 'Tecnologia Leaflet',

    'landing_problem_title': 'Pare de Gerenciar Redes com',
    'landing_problem_highlight': 'Planilhas',
    'landing_problem_desc': 'Métodos tradicionais como Google Earth + Excel são propensos a erros, não atualizam em tempo real e ficam incontroláveis quando a rede cresce. Você precisa de um sistema que entenda fibra óptica, perda de sinal e topologia.',
    'landing_problem_1': 'Sem visibilidade de portas livres',
    'landing_problem_2': 'Documentação manual sempre desatualizada',
    'landing_problem_3': 'Difícil rastrear perda de sinal e fusões',
    'landing_problem_4': 'Colaboração em equipe é um pesadelo',
    'landing_error_connection': 'Erro: Limite de conexões excedido',

    'landing_features_title': 'Tudo Que Você Precisa para Escalar',
    'landing_features_desc': 'Do planejamento à implantação, nossa ferramenta cobre cada aspecto da sua operação ISP.',
    'landing_feat_maps': 'Mapas Interativos',
    'landing_feat_maps_desc': 'Visualize toda sua rede em mapas de alta performance. Zoom, pan e edições com precisão.',
    'landing_feat_cable': 'Gestão de Cabos e Fusões',
    'landing_feat_cable_desc': 'Rastreie cada fibra, fusão e conexão de splitter. Cálculo automático de perda de sinal.',
    'landing_feat_team': 'Multi-Tenant e Equipes',
    'landing_feat_team_desc': 'Gerencie múltiplos projetos e atribua controle de acesso baseado em cargos para seu time de engenharia.',
    'landing_feat_snap': 'Ferramentas de Design Inteligente',
    'landing_feat_snap_desc': 'Ferramentas de desenho que "grudam" na infraestrutura existente, acelerando seu processo de design em 50%.',
    'landing_feat_bom': 'Inventário e Relatórios',
    'landing_feat_bom_desc': 'Gere BOM (Lista de Materiais) automaticamente. Saiba exatamente quanto de cabo você precisa.',
    'landing_feat_import': 'Importação/Exportação',
    'landing_feat_import_desc': 'Importe arquivos KMZ/KML do Google Earth sem problemas e exporte projetos para equipes de campo.',

    'landing_perf_badge': 'Ultra Performance',
    'landing_perf_title': 'Feito para Milhões de Elementos',
    'landing_perf_desc': "Não deixe o lag te atrasar. Nosso motor é otimizado para navegar em redes massivas com zero latência. Lide com implantações em cidades inteiras com milhares de CTOs e POPs sem problemas.",
    'landing_stat_elements': 'Elementos renderizados',
    'landing_stat_scroll': 'Rolagem suave',
    'landing_stat_search': 'Tempo de busca',
    'landing_stat_uptime': 'Disponibilidade',
    'landing_graph_engine': 'Motor de Renderização',
    'landing_graph_active': 'Ativo',
    'landing_graph_load': 'Carga do Sistema: 5%',

    'landing_sec_title': 'Segurança de Nível Empresarial',
    'landing_sec_desc': 'Seus dados de rede são seu ativo mais valioso. Nós tratamos com a proteção que merecem.',
    'landing_sec_1': 'Criptografia Ponta-a-Ponta',
    'landing_sec_2': 'Backups Diários',
    'landing_sec_3': 'Controle de Acesso por Cargo',
    'landing_sec_4': 'Logs de Auditoria',
    'landing_sec_5': 'SLA de 99.9%',

    'landing_steps_title': 'Comece em 3 Passos Simples',
    'landing_step_1_title': 'Crie seu Workspace',
    'landing_step_1_desc': 'Cadastre-se e crie sua primeira área de projeto em segundos.',
    'landing_step_2_title': 'Desenhe ou Importe',
    'landing_step_2_desc': 'Desenhe sua rede do zero ou importe arquivos KMZ existentes instantaneamente.',
    'landing_step_3_title': 'Gerencie e Escale',
    'landing_step_3_desc': 'Convide seu time e comece a gerenciar as operações.',

    'landing_cta_title': 'Pronto para modernizar seu ISP?',
    'landing_cta_desc': 'Junte-se a centenas de engenheiros de rede que confiam no FTTH Master para suas operações diárias.',
    'landing_cta_btn': 'Começar Grátis',

    'landing_footer_desc': 'O padrão profissional para design e gestão de redes FTTH.',
    'landing_footer_product': 'Produto',
    'landing_footer_company': 'Empresa',
    'landing_footer_legal': 'Legal',
    'landing_footer_rights': '© 2024 FTTH Master. Todos os direitos reservados.',

    // Pricing
    'pricing_title': 'Planos Simples e Transparentes',
    'pricing_desc': 'Escolha o plano ideal para o estágio de crescimento do seu provedor.',
    'plan_free': 'Grátis',
    'plan_basic': 'Básico',
    'plan_inter': 'Intermediário',
    'plan_unlimited': 'Ilimitado',
    'price_free': 'Grátis',
    'month': '/mês',
    'feature_projects': '{count} Projetos',
    'feature_users': '{count} Usuários',
    'feature_ctos': '{count} CTOs',
    'feature_pops': '{count} POPs',
    'feature_unlimited': 'Ilimitado',
    'plan_cta': 'Começar Agora',
    'most_popular': 'Mais Popular',
    'feature_1_project': '1 Projeto',
    'feature_1_user': '1 Usuário',
    'copy_coordinates': 'Copiar Coordenadas',
    'open_google_maps': 'Abrir no Google Maps',
    'coordinates': 'Coordenadas',
    'pinned_location': 'Salvar como',
    'viability_status': 'Viabilidade',
    'viability_available': 'Viabilidade Disponível',
    'viability_unavailable': 'Sem Viabilidade',
    'distance_nearest': 'Dist. Aproximada: {dist}m',
    'convert_to_cto': 'Salvar como Caixa',
    'convert_to_pole': 'Salvar como Poste',
    'remove_pin': 'Remover Pin',
    'feature_basic_maps': 'Mapas Básicos',
    'feature_5_projects': '5 Projetos',
    'feature_3_users': '3 Usuários',
    'feature_email_support': 'Suporte por Email',
    'feature_unlimited_all': 'Tudo Ilimitado',
    'feature_priority_support': 'Suporte Prioritário',
    'feature_auto_backup': 'Backup Automático',
    'feature_projects_unlimited': 'Projetos Ilimitados',
    'feature_users_unlimited': 'Usuários Ilimitados',
    'feature_ctos_unlimited': 'CTOs Ilimitados',

    // Login & Dashboard
    'enter_btn': 'Entrar no Sistema',
    'login_title': 'FTTH Planner',
    'login_subtitle': 'Entre com suas credenciais',
    'login_email_placeholder': 'Email',
    'login_password_placeholder': 'Senha',
    'login_button_loading': 'Entrando...',
    'login_button': 'Entrar',
    'login_create_account': 'Criar nova conta',
    'login_feature_label': 'Destaque',
    'login_feature_title': 'Editor de Fusão',
    'back_to_home': 'Voltar ao Início',
    'register_page_title': 'Criar Conta',
    'register_subtitle': 'Junte-se ao FTTH Master Planner',
    'register_company_placeholder': 'Nome da Empresa (Provedor)',
    'register_password_placeholder': 'Senha',
    'register_confirm_password_placeholder': 'Confirmar Senha',
    'register_button': 'Registrar Conta',
    'register_already_have_account': 'Já tem uma conta? Entrar',
    'register_error_empty': 'Por favor, preencha todos os campos.',
    'register_error_match': 'As senhas não coincidem.',
    'register_btn': 'Criar Conta',
    'no_account': 'Não tem uma conta?',
    'already_have_account': 'Já tem uma conta?',
    'register_title': 'Criar Conta FTTH Planner',
    'back_to_login': 'Voltar para o Login',
    'registration_success': 'Conta criada! Agora você pode entrar.',
    'registration_failed': 'Falha no registro. Usuário já pode existir.',
    'welcome': 'Bem-vindo, {name}',
    'logout': 'Sair',
    'my_projects': 'Meus Projetos',
    'create_new_project_btn': 'Criar Novo Projeto',
    'no_projects': 'Nenhum projeto encontrado. Crie o primeiro!',
    'last_modified': 'Última modificação: {date}',
    'open_project': 'Abrir Projeto',
    'exit_project': 'Sair para o Painel',
    'delete_project_confirm': 'Tem certeza que deseja deletar o projeto "{name}"?',
    'project_updated': 'Projeto atualizado com sucesso!',
    'toast_project_deleted': 'Projeto excluído com sucesso!',
    'error_project_update': 'Falha ao atualizar projeto.',
    'error_project_delete': 'Falha ao excluir projeto.',

    // App / Sidebar
    'app_title': 'Planejador FTTx',
    'active_project': 'Projeto Ativo',
    'tools': 'Ferramentas',
    'settings': 'Configurações',
    'system_settings': 'Configurações',
    'view_options': 'Opções de Visualização',
    'toggle_labels': 'Nomes',
    'sidebar_collapse': 'Recolher Menu',
    'sidebar_expand': 'Expandir Menu',
    'menu': 'Menu',
    'home': 'Início',
    'mode_view': 'Seleção / Nav',
    'mode_move': 'Mover Elementos',
    'mode_otdr': 'OTDR Trace',
    'sidebar_pole': 'Poste',
    'mode_add_cto': 'Adicionar CTO',
    'mode_add_pop': 'Adicionar POP',
    'mode_draw_cable': 'Desenhar Cabo',
    'mode_connect_cable': 'Conectar / Sangria',
    'ctx_remove_cable': 'Remover cabo da caixa',
    'ctx_edit_cable': 'Editar cabo',
    'ctx_next_box': 'Ir para Próxima Caixa',
    'action_flip': 'Inverter lado',
    'action_rotate': 'Girar',
    'ctx_details': 'Detalhes',
    'toast_select_next_box': 'Selecione a caixa de destino para navegar',
    'error_cable_fully_connected': 'Cabo já conectado em ambas as pontas',
    'select_project_placeholder': 'Selecione o Projeto...',
    'ai_audit': 'Auditoria IA',
    'analyzing': 'Analisando...',
    'tooltip_view': 'Navegação: Clique para editar. Elementos estão travados.',
    'tooltip_move': 'Modo Mover: Arraste CTOs ou POPs para ajustar a posição.',
    'tooltip_otdr': 'Modo OTDR: Clique em um cabo para localizar um evento.',
    'tooltip_add_cto': 'Posicionamento: Clique no mapa para adicionar CTO.',
    'tooltip_add_pop': 'Posicionamento: Clique no mapa para adicionar um POP (Central).',
    'tooltip_add_pole': 'Posicionamento: Clique no mapa para adicionar um poste.',
    'tooltip_draw_cable': 'Desenhando: Clique no mapa ou nó para finalizar o cabo.',
    'tooltip_draw_cable_start': 'Desenhando: Clique no mapa ou Nó para iniciar o cabo.',
    'tooltip_connect': 'Conexão: Clique no cabo para criar ponto de SANGRIA. Arraste até o Nó.',
    'ai_report_title': 'Relatório de Engenharia IA',
    'deployment_progress': 'Progresso de Implantação',
    'search_placeholder': 'Buscar CTO, POP ou Coordenadas...',
    'search_no_results': 'Nenhum resultado',

    // New Sidebar Keys
    'sidebar_operation': 'Operação',
    'sidebar_select': 'Selecionar',
    'sidebar_move': 'Mover',
    'sidebar_design': 'Design de Rede',
    'sidebar_add_cto': 'Nova CTO',
    'sidebar_add_pop': 'Novo POP',
    'sidebar_draw_cable': 'Desenhar Cabo',
    'sidebar_draw_cable_desc': 'Clique p/ múltiplos pontos',
    'sidebar_connect_cable': 'Conectar/Editar Cabos',
    'sidebar_connect_cable_desc': 'Ajustar conexões e geometria',
    'registrations': 'Cadastros',
    'manage_networks_desc': 'Gerencie e organize suas redes FTTH.',
    'cables': 'Cabos',
    'search_generic': 'Buscar...',
    'reg_poste': 'Poste',
    'reg_caixa': 'Caixa',
    'reg_cabo': 'Cabo',
    'reg_splitter': 'Splitter',
    'reg_fusao': 'Fusão',
    'new_fusion': 'Nova Fusão',
    'edit_fusion': 'Editar Fusão',
    'fusion_catalog_desc': 'Gerencie os tipos de fusão e atenuação.',
    'backup': 'Backup',
    'upgrade_now': 'Fazer Upgrade',
    'manage_subscription': 'Gerenciar Assinatura',
    'trial': 'Teste',
    'expires': 'Expira',
    'days': 'dias',
    'registration_title': 'Cadastro: {name}',
    'registration_placeholder_desc': 'Módulo de cadastro de {name} em desenvolvimento.',
    'module_under_development': 'Este módulo está em desenvolvimento.',
    'splitter_catalog_desc': 'Gerencie os tipos de splitter do catálogo.',
    'add_splitter': 'Adicionar Splitter',
    'confirm_delete': 'Tem certeza?',
    'search_splitters': 'Buscar splitters...',
    'edit_splitter': 'Editar Splitter',
    'new_splitter': 'Novo Splitter',
    'splitter_name': 'Nome',
    'select_splitter': 'Selecionar Splitter',
    'select_fusion_type': 'Selecionar Tipo de Fusão',
    'select_fusion_type_desc': 'Escolha o tipo de fusão para adicionar.',
    'splitter_type': 'Tipo',
    'splitter_mode': 'Modo',
    'inputs': 'Entradas',
    'outputs': 'Saídas',
    'attenuation': 'Atenuação',
    'attenuation_db': 'Atenuação (dB)',
    'description': 'Descrição',

    'loading': 'Carregando...',
    'loading_diagram': 'Carregando diagrama...',
    'error_saving_splitter': 'Erro ao salvar splitter',
    'sidebar_add_pole': 'Adicionar Poste',
    'sidebar_add_pole_desc': 'Posicionar Manualmente',
    'insertion_options': 'Opções de inserção',

    'attenuation_port1': 'Atenuação Porta 1 (dB)',
    'attenuation_port2': 'Atenuação Porta 2 (dB)',
    'splitter_ports': 'Portas',
    'splitter_in': 'Ent',
    'splitter_out': 'Sai',
    'splitter_mode_balanced': 'Balanceado',
    'splitter_mode_unbalanced': 'Desbalanceado',

    // OLT Catalog
    'reg_olt': 'OLT',
    'olt_catalog_desc': 'Gerencie seus modelos de OLT e potência de saída.',
    'search_olts': 'Buscar OLTs...',
    'no_olts_found': 'Nenhuma OLT encontrada.',
    'olt_name': 'Modelo',
    'output_power': 'Potência de Saída (dBm)',
    'olt_slots': 'Slots',
    'ports_per_slot': 'Portas/Slot',
    'edit_olt': 'Editar OLT',
    'new_olt': 'Nova OLT',
    'add_olt': 'Adicionar OLT',
    'error_saving_olt': 'Erro ao salvar OLT',

    // Toasts
    'toast_imported': 'Importado {ctos} CTOs e {cables} Cabos',
    'toast_cto_added': 'CTO adicionada com sucesso',
    'toast_pop_added': 'POP adicionado com sucesso',
    'toast_cto_splicing_saved': 'Fusões da CTO salvas',
    'toast_pop_saved': 'Configuração do POP salva',
    'toast_cto_deleted': 'CTO removida com sucesso',
    'toast_pole_deleted': 'Poste removido com sucesso',
    'toast_pole_added': 'Poste adicionado com sucesso',
    'toast_cable_updated': 'Cabo atualizado',
    'toast_cable_deleted': 'Cabo deletado',
    'toast_cable_created': 'Cabo criado com sucesso',
    'toast_cable_connected_start': 'Início do cabo conectado a {name}',
    'toast_cable_connected_end': 'Fim do cabo conectado a {name}',
    'toast_cable_split': 'Cabo sangrado e conectado a {name}',
    'toast_cable_anchored_pole': 'Cabo ancorado ao poste {name}',
    'error_cto_duplicate_cable': 'Este cabo já está conectado a esta CTO.',
    'toast_auto_snap_success': 'Auto-conexão/Sangria de {count} pontos em {distance}m.',
    'toast_poles_imported': '{count} postes importados com sucesso!',
    'toast_poles_import_error': 'Erro ao importar postes.',
    'error_cable_endpoint_missing': 'Cabo solto na outra ponta',
    'error_target_not_found': 'Destino não encontrado',
    'toast_select_next_cable': 'Selecione outro cabo para conectar',
    'toast_cable_disconnected': 'Cabo desconectado',
    'import_error': 'Falha ao importar arquivo. Veja o console.',
    'import_no_geo': 'Nenhuma geometria compatível (Pontos ou Linhas) encontrada.',

    // OTDR Messages & Errors
    'otdr_title': 'Calculadora OTDR',
    'otdr_distance_lbl': 'Distância da Medição (m)',
    'otdr_direction': 'Direção',
    'otdr_from_start': 'Do Início (Nó A)',
    'otdr_from_end': 'Do Fim (Nó B)',
    'otdr_locate': 'Localizar Evento',
    'otdr_result': 'Local do Evento',
    'otdr_error_length': 'Distância excede o tamanho do cabo ({length}m)',
    'otdr_trace_start_error': 'Rastreio OTDR: Por favor comece de uma porta de fibra de cabo.',
    'otdr_cable_not_found': 'Erro OTDR: Cabo não encontrado.',
    'otdr_conn_mismatch': 'Erro OTDR: Inconsistência na conectividade do cabo.',
    'otdr_end_open': 'OTDR: Fim da fibra alcançado (Ponta Aberta).',
    'otdr_next_node_error': 'Erro OTDR: Próximo nó não encontrado.',
    'otdr_fiber_end_node': 'OTDR: Fibra termina em {node} (Não fusionada).',
    'otdr_event_equipment': 'OTDR: Evento em {node} (Conexão com Equipamento).',
    'otdr_max_depth': 'OTDR: Profundidade máxima de rastreio atingida.',
    'otdr_success_cable': 'Localizado no cabo {name}',
    'otdr_inside_cto': 'Dentro da CTO {name}',
    'otdr_trace_msg': 'Rastrear a partir da fibra selecionada',
    'otdr_instruction_banner': 'Clique em uma porta de fibra para medir a distância.',
    'otdr_event_tooltip': 'Evento OTDR',

    // Splitter Power Modal
    'optical_budget': 'Orçamento Óptico',
    'optical_path_for': 'Caminho óptico para',
    'no_signal': 'Sem Sinal (Desconectado)',
    'status_ok': 'OK (Ideal)',
    'status_marginal': 'Marginal (Alerta)',
    'status_fail': 'Falha (Crítico)',

    'type_CABLE': 'Cabo',
    'type_SPLITTER': 'Splitter',
    'type_FUSION': 'Fusão',
    'type_CONNECTOR': 'Conector / DIO',
    'type_OLT': 'OLT',

    // Common
    'save': 'Salvar',
    'cancel': 'Cancelar',
    'delete': 'Deletar',

    'name': 'Nome',
    'status': 'Status',
    'type': 'Tipo',
    'color': 'Cor',
    'id': 'ID',
    'manage_splicing': 'Gerenciar Fusões',
    'manage_pop': 'Gerenciar Rack e Patching',
    'unsaved_changes': 'Alterações Não Salvas',
    'unsaved_changes_msg': 'Você tem alterações não salvas. Deseja salvá-las antes de sair?',
    'discard': 'Descartar',
    'save_and_close': 'Salvar e Sair',
    'save_or_done': 'Salvar / Sair',
    'clear_connections_confirm': 'Tem certeza que deseja limpar TODAS as conexões? Isso não pode ser desfeito.',
    'changes_saved': 'Alterações salvas com sucesso',
    'position_saved': 'Posição salva com sucesso!',
    'save_position': 'Salvar Posição',
    'moving_node': 'Movendo Elemento...',
    'editing_cable': 'Editando Cabo...',
    'connecting_cable': 'Conectando Cabos...',
    'finish': 'Concluir',
    'finish_cable': 'Finalizar Cabo',
    'connection_cancelled': 'Conexão Cancelada',
    'meters': 'metros',
    'saved': 'Salvo',
    'done': 'Concluir',
    'clear_all': 'Limpar Tudo',
    'confirm_delete_equip_msg': 'Tem certeza que deseja deletar {name}?',
    'delete_warning_msg': 'Aviso: Todas as conexões associadas a este {type} serão removidas permanentemente.',

    // Statuses
    'status_PLANNED': 'Em Projeto',
    'status_NOT_DEPLOYED': 'Não Implantado',
    'status_DEPLOYED': 'Implantado',
    'status_CERTIFIED': 'Certificado',
    'status_ANALYSING': 'Em Análise',
    'status_LICENSED': 'Licenciado',

    // Pole Details
    'edit_pole': 'Editar Poste',
    'pole_properties': 'Propriedades do Poste',
    'pole_type': 'Tipo de Poste',
    'selection_pole_type': 'Tipo de Poste',
    'pole_height_placeholder': 'Ex: 10',
    'delete_pole_btn': 'Deletar Poste',
    'confirm_delete_pole_msg': 'Tem certeza que deseja deletar {name}?',
    'confirm_delete_pole_confirm': 'Deseja excluir este poste?',

    // CTO/POP Details
    'edit_cto': 'Editar CTO',
    'edit_pop': 'Editar POP',
    'cto_info': 'Informações da CTO',
    'pop_info': 'Informações do POP',

    'connections': 'Conexões',
    'spliced': 'Fusões',
    'patched': 'Manobras',

    'fusion_tool_active': 'Modo Fusão: Clique para adicionar fusão',
    'splitters': 'Splitters',
    'equipment': 'Equipamentos',
    'backbone_cables': 'Cabos Backbone',
    'confirm_delete_cto_msg': 'Confirmar deleção de {name}? Todos os cabos conectados serão removidos.',
    'confirm_delete_pop_msg': 'Confirmar deleção do POP {name}? Isso removerá racks, equipamentos e cabos.',
    'delete_cto_btn': 'Deletar CTO',
    'delete_pop_btn': 'Deletar POP',

    // Cable Editor
    'edit_cable': 'Editar Cabo',

    'cable_name': 'Nome do Cabo',
    'fiber_count': 'Qtd. Fibras',
    'loose_tubes': 'Tubos Loose',
    'tube': 'Tubo',
    'estimated_length': 'Comprimento Est.',
    'map_color': 'Cor no Mapa',
    'disabled': 'Desativado',
    'save_changes': 'Salvar Alterações',
    'confirm_delete_cable_msg': 'Confirmar deleção de {name}? Isso removerá as fusões associadas.',
    'color_standard': 'Padrão de Cores',
    'standard_abnt': 'ABNT (Brasil)',
    'standard_eia': 'EIA-598-A (Intl)',
    'toast_mode_move_node': 'Modo mover ativado',

    // Project Manager / Create Modal
    'project_manager': 'Gerenciador de Projetos',
    'create_project': 'Criar Projeto',
    'new_project_placeholder': 'Nome do Projeto (ex: Expansão Centro)',
    'import_kmz_title': 'Importar KMZ/KML para Projeto Atual',
    'import_kmz_desc': 'Clique para enviar arquivo .kmz ou .kml',
    'processing': 'Processando...',
    'your_projects': 'Seus Projetos',
    'load_project': 'Carregar',
    'delete_last_project_error': 'Não é possível deletar o último projeto.',
    'items_count': 'Itens: {ctos} CTOs, {cables} Cabos',
    'search_location': 'Localização Inicial',
    'search_location_placeholder': 'Pesquise cidade ou endereço...',
    'searching_location': 'Buscando...',
    'no_location_results': 'Local não encontrado',

    'create_project_modal_title': 'Criar Novo Projeto',
    'edit_project': 'Editar Projeto',
    'map_instruction': 'Arraste o mapa ou clique para definir o centro do projeto.',
    'confirm_create': 'Criar Projeto',
    'snap_distance_lbl': 'Distância de Imã (metros)',
    'snap_distance_help': 'Distância máxima para um cabo "grudar" automaticamente em uma caixa (CTO/POP) ao arrastar.',

    // CTO Internal Editor
    'splicing_title': '{name}',
    'dio_splicing_title': 'Fusão DIO: {name}',
    'splicing_help': 'Role para Zoom. Arraste fundo para mover. Duplo-clique remove pontos.',

    'add_fusion': 'Fusão',
    'auto_splice': 'Auto Passante',
    'reset_connections': 'Resetar Conexões',
    'drop_to_connect': 'Solte na porta para conectar, ou no fundo para desconectar.',
    'moving_point': 'Movendo ponto de controle...',
    'panning': 'Movendo tela',
    'general_help': 'Arraste portas para conectar. Clique nas linhas para criar curvas. Duplo-clique para remover. Renomeie com duplo-clique.',
    'rename_fusion': 'Renomear Ponto de Fusão:',
    'export_pdf': 'Exportar PDF',
    'generating_pdf': 'Gerando...',
    'tool_vfl': 'VFL (Caneta Óptica)',
    'vfl_active_msg': 'VFL Ativo: Clique em qualquer porta para injetar a luz.',

    'vfl_source_label': 'Fonte: {name}',
    'turn_off': 'Desligar',
    'source_cable': 'Cabo Origem',
    'target_cable': 'Cabo Destino',
    'perform_splice': 'Fusionar Tudo',
    'splice_success': 'Fusionadas {count} fibras com sucesso.',
    'smart_align': 'Alinhamento Inteligente',

    // DIO Editor Strings
    'link_cables': 'Vincular Cabos',
    'linked_cables': 'Cabos Vinculados',
    'no_cables_linked': 'Nenhum Cabo Vinculado',
    'link_cables_help': 'Você pode vincular cabos a este DIO usando o botão acima.',
    'connect_fiber_tray': 'Conectar Fibra à Bandeja DIO',
    'connected_to_port': 'Atualmente conectado à Porta {port}',
    'select_tray_port_help': 'Selecione uma porta da bandeja abaixo para fusionar esta fibra.',
    'green_light_help': 'Luzes verdes indicam sinal OLT ativo fluindo para o cabo.',
    'select_target_port_dio': 'Selecione uma Porta de Destino em {name}',
    'currently_connected': 'Atualmente Conectado',
    'port_occupied_splice': 'Porta ocupada por outra fusão',
    'port_has_patch_cord': 'Porta possui patch cord (Fusão permitida)',
    'port_available': 'Disponível',
    'linked_to_dio': 'Vinculado a {name}',
    'legend_active_signal': 'Sinal Ativo',
    'legend_vfl_source': 'Fonte VFL',
    'unit_meters': 'METROS',
    'click_to_manage': 'Clique para Gerenciar',
    'click_to_connect': 'Clique para Conectar',
    'splice_trays': 'Bandejas de Fusão',

    // New Translations for Trays
    'tray': 'Bandeja',
    'trays': 'Bandejas',

    // Box Catalog
    'box_catalog': 'Catálogo de Caixas',
    'box_catalog_desc': 'Gerencie os modelos de caixas (CTO/CEO) disponíveis.',
    'box_model': 'Modelo de Caixa',
    'select_box_model': 'Selecione Modelo...',
    'reserve_loop_length': 'Reserva Técnica',
    'reserve': 'Reserva',
    'brand': 'Marca',
    'model': 'Modelo',
    'ident_color': 'Cor de Identificação',
    'type_cto_termination': 'CTO (Terminação)',
    'type_ceo_splice': 'CEO (Emenda)',
    'edit_box': 'Editar Caixa',
    'new_box': 'Nova Caixa',
    'search_placeholder_box': 'Buscar por nome, marca ou modelo...',
    'add_new': 'Adicionar Nova',
    'details_placeholder': 'Detalhes adicionais...',
    'bm_cancel': 'Cancelar',

    // Pole Catalog
    'pole_catalog': 'Catálogo de Postes',
    'pole_catalog_desc': 'Gerencie os modelos de postes disponíveis.',
    'pole_height': 'Altura (m)',
    'pole_strength': 'Resistência (daN)',
    'pole_shape': 'Formato',
    'shape_circular': 'Circular',
    'shape_duplot': 'Duplo T',
    'shape_square': 'Quadrado',
    'new_pole': 'Novo Poste',
    'error_save': 'Falha ao salvar',


    // POP Editor
    'pop_editor_title': 'Gerenciamento POP: {name}',
    'add_dio': 'Add DIO',
    'olt_ports': 'Portas PON',
    'dio_ports': 'Portas',
    'rack_view': 'Visão do Rack',

    // Users Module
    'users': 'Usuários',
    'users_manage_desc': 'Gerencie membros da equipe e seus cargos.',
    'add_user': 'Adicionar Usuário',
    'username': 'Usuário',
    'role': 'Cargo',
    'created_at': 'Criado em',
    'actions': 'Ações',
    'no_users_found': 'Nenhum usuário encontrado.',
    'role_member': 'Membro',
    'role_admin': 'Admin',
    'role_owner': 'Dono',
    'password': 'Senha',
    'edit_user': 'Editar Usuário',
    'update': 'Atualizar',
    'confirm_delete_user_msg': 'Tem certeza que deseja deletar o usuário {username}?',
    'create': 'Criar',

    // User Management Errors
    'error_username_taken': 'Este nome de usuário já está em uso.',
    'error_password_length': 'A senha deve ter pelo menos 6 caracteres.',
    'error_cannot_delete_self': 'Você não pode deletar sua própria conta.',
    'error_generic': 'Ocorreu um erro inesperado.',
    'error_create_user': 'Falha ao criar usuário.',
    'error_delete_user': 'Falha ao deletar usuário.',

    // Map Layers
    'map_street': 'Map rua',
    'map_satellite': 'Satélite',
    'map_layers': 'Camadas',
    'layer_cables': 'Cabos',
    'layer_ctos': 'CTOs',
    'layer_pops': 'POPs',

    // Backup
    'backup_title': 'Gerenciador de Backup',
    'backup_desc': 'Gerencie os backups do sistema. Backups diários são executados automaticamente às 02:00 AM.',
    'create_backup': 'Criar Backup',
    'backup_filename': 'Nome do Arquivo',
    'backup_date': 'Data',
    'backup_size': 'Tamanho',
    'download': 'Baixar',
    'confirm_delete_backup': 'Tem certeza que deseja deletar este backup?',
    'backup_success': 'Backup criado com sucesso',
    'backup_created_at': 'Criado em',
    'backup_manual': 'Manual',

    'backup_auto': 'Automático',
    'no_backups': 'Nenhum backup encontrado.',
    'restore': 'Restaurar',
    'upload_restore': 'Enviar & Restaurar',
    'restore_confirm': 'AVISO: Isso irá apagar TODOS os dados de rede atuais (CTOs, Cabos, POPs, Projetos) e substituí-los pelo backup. Isso não pode ser desfeito. Tem certeza?',
    'restore_success': 'Sistema restaurado com sucesso. Recarregando...',
    'apply': 'Aplicar'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('ftth_language');
      return (saved as Language) || 'pt';
    }
    return 'pt';
  });

  React.useEffect(() => {
    localStorage.setItem('ftth_language', language);
  }, [language]);

  const t = (key: string, params?: Record<string, string | number>) => {
    let text = translations[language][key as keyof typeof translations['en']] || key;

    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
