
import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const translations = {
  en: {
    // Theme
    'theme_light': 'Light Mode',
    'theme_dark': 'Dark Mode',

    // Login & Dashboard
    'enter_btn': 'Enter System',
    'register_btn': 'Create Account',
    'no_account': "Don't have an account?",
    'already_have_account': 'Already have an account?',
    'register_title': 'Create FTTx Planner Account',
    'back_to_login': 'Back to Login',
    'registration_success': 'Account created! You can now log in.',
    'registration_failed': 'Registration failed. Username might be taken.',
    'login_title': 'FTTx Planner',
    'login_subtitle': 'Enter your credentials',
    'login_email_placeholder': 'Email',
    'login_password_placeholder': 'Password',
    'login_button_loading': 'Logging in...',
    'login_button': 'Login',
    'login_create_account': 'Create new account',
    'forgot_password': 'Forgot password?',
    'forgot_password_title': 'Recover Password',
    'forgot_password_subtitle': 'Enter your email to receive a recovery link.',
    'forgot_password_send': 'Send Recovery Link',
    'reset_password_title': 'New Password',
    'reset_password_subtitle': 'Enter your new password below.',
    'reset_password_button': 'Reset Password',
    'reset_password_success': 'Password reset successfully!',
    'reset_password_error': 'Invalid or expired token.',
    'forgot_password_success': 'Email sent! Please check your inbox for the recovery link.',
    'forgot_password_error_generic': 'Error sending email. Please try again later.',
    'forgot_password_error_connection': 'Connection error. Please check your internet.',
    'reset_password_error_mismatch': 'Passwords do not match.',
    'reset_password_error_length': 'Password must be at least 6 characters.',
    'reset_password_error_connection': 'Server connection error.',
    'reset_password_success_redirect': 'Password saved! Redirecting to login...',
    'login_feature_label': 'Feature',
    'login_feature_title': 'Fusion Editor',
    'back_to_home': 'Back to Home',
    'company_settings_title': 'Company Settings',
    'company_settings_subtitle': 'Manage your company identity and contact information',
    'company_name_label': 'Company Name',
    'company_logo_label': 'Company Logo',
    'company_logo_hint': 'Recommended: Square image, PNG or JPG',
    'company_cnpj_label': 'CNPJ / Tax ID',
    'company_phone_label': 'Contact Phone',
    'company_email_label': 'Business Email',
    'company_website_label': 'Website',
    'company_address_label': 'Address',
    'company_city_label': 'City',
    'company_state_label': 'State',
    'company_zip_label': 'ZIP / Postal Code',
    'company_save_button': 'Save Settings',
    'company_save_success': 'Company settings updated successfully!',
    'company_save_error': 'Failed to update company settings',
    'company_upload_logo': 'Upload Logo',
    'company_uploading': 'Uploading...',
    'register_page_title': 'Create FTTx Planner Account',
    'register_subtitle': 'Join FTTx Master Planner',
    'register_company_placeholder': 'Company Name (ISP)',
    'register_phone_placeholder': 'Phone Number',
    'register_password_placeholder': 'Password',
    'register_confirm_password_placeholder': 'Confirm Password',
    'register_button': 'Register Account',
    'register_already_have_account': 'Already have an account? Login',
    'register_error_empty': 'Please fill all fields.',
    'register_error_match': 'Passwords do not match.',
    'welcome': 'Welcome, {name}',
    'logout': 'Logout',
    'my_projects': 'My Projects',
    'create_new_project_btn': 'Create New Project',
    'no_projects': 'No projects found. Create your first one!',
    'last_modified': 'Last modified: {date}',
    'open_project': 'Open Project',
    'exit_project': 'Exit to Dashboard',
    'delete_project_confirm': 'Are you sure you want to delete project "{name}"?',
    'project_updated': 'Project updated successfully!',
    'toast_project_deleted': 'Project deleted successfully!',
    'error_project_update': 'Failed to update project.',
    'error_project_delete': 'Failed to delete project.',
    'error_saving_changes': 'Error saving changes. Please try again.',
    'error_permission_denied': 'Access denied: you do not have permission to perform this action.',

    // App / Sidebar
    'app_title': 'FTTx Planner',
    'active_project': 'Active Project',
    'tools': 'Tools',
    'settings': 'Settings',
    'system_settings': 'Settings',
    'view_options': 'View Options',
    'zoom_in': 'Zoom In',
    'zoom_out': 'Zoom Out',
    'center_view': 'Center View',
    'show_all': 'Show All Items',
    'toggle_labels': 'Labels',
    'sidebar_collapse': 'Collapse Menu',
    'sidebar_expand': 'Expand Menu',
    'menu': 'Menu',
    'home': 'Home',
    'mode_view': 'Selection / Nav',
    'mode_move': 'Move Elements',
    'mode_otdr': 'OTDR Trace',
    'mode_add_cto': 'Place CTO',
    'mode_add_pop': 'Place POP',
    'mode_draw_cable': 'Draw Cable',
    'mode_connect_cable': 'Connect Cable',
    'select_project_placeholder': 'Select Project...',
    'ai_audit': 'AI Network Audit',
    'analyzing': 'Analyzing...',
    'tooltip_view': 'Navigation Mode: Click markers or cables to select/edit.',
    'tooltip_move': 'Move Mode: Drag CTOs or POPs to adjust position.',
    'tooltip_otdr': 'OTDR Mode: Click a cable to locate a distance/event.',
    'tooltip_add_cto': 'Placement Mode: Click on map to add CTO.',
    'tooltip_add_pop': 'Placement Mode: Click on map to add a Central Office (POP).',
    'tooltip_add_pole': 'Placement Mode: Click on map to add a Pole.',
    'tooltip_draw_cable': 'Drawing: Click anywhere to draw cable. Click markers to snap.',
    'tooltip_draw_cable_start': 'Drawing: Click map or Node to start cable.',
    'tooltip_connect': 'Connection Mode: Click cable line to add SPLIT point. Drag point to Node to connect.',
    'right_click_delete_point': 'Right-click or Double-click to remove point',
    'ai_report_title': 'AI Engineer Report',
    'deployment_progress': 'Deployment Progress',
    'search_placeholder': 'Search CTO, POP or Coordinates...',
    'search_no_results': 'No results found',

    // New Sidebar Keys
    'sidebar_operation': 'Operation',
    'sidebar_select': 'Select',
    'sidebar_move': 'Move',
    'sidebar_design': 'Network Design',
    'sidebar_pole': 'Pole',
    'sidebar_add_cto': 'New CTO',
    'sidebar_add_pop': 'New POP',
    'sidebar_draw_cable': 'Draw Cable',
    'sidebar_draw_cable_desc': 'Click for multiple points',
    'sidebar_connect_cable': 'Connect/Edit Cables',
    'sidebar_connect_cable_desc': 'Adjust connections & geometry',
    'registrations': 'Registrations',
    'manage_networks_desc': 'Manage and organize your FTTx networks.',
    'cables': 'Cables',
    'search_generic': 'Search...',
    'reg_poste': 'Pole',
    'reg_caixa': 'Box',
    'reg_cabo': 'Cable',
    'reg_fusao': 'Fusion Types',
    'reg_olt': 'Active Equipment',
    'reg_clientes': 'Customers',
    'users': 'Users',
    'backup': 'Backup',
    'upgrade_now': 'Upgrade Now',
    'upgrade_exclusive_msg': 'This feature is exclusive to subscribers. Your data is safe, but an active plan is required to export.',
    'manage_subscription': 'Manage Subscription',
    'trial': 'Trial',
    'expires': 'Expires',
    'days': 'days',
    'registration_title': 'Registration: {name}',
    'registration_placeholder_desc': '{name} registration module under development.',
    'module_under_development': 'This module is currently under development.',
    'draw_customer_drop': 'Draw Cable',
    'draw_customer_drop_desc': 'Draw a cable from a CTO to a customer location.',

    // Active Equipment (OLT) Catalog
    'olt_catalog_desc': 'Manage your active equipment models and specifications.',
    'search_olts': 'Search equipment...',
    'no_olts_found': 'No equipment found.',
    'olt_name': 'Model',
    'output_power': 'Output Power (dBm)',
    'olt_slots': 'Slots',
    'ports_per_slot': 'Ports/Slot',
    'edit_olt': 'Edit OLT',
    'new_olt': 'New OLT',
    'error_saving_olt': 'Error saving equipment',
    'equipment_preview_msg': 'Creates a {type} with {total} ports ({slots} slots × {ports} ports).',
    'olt_output_power_help': 'Class B+: ~3dBm, C+: ~7dBm',
    'power_consumption': 'Power Consumption (W)',
    'reg_active_equipment': 'Active Equipment',
    'equipment_name': 'Equipment Name',

    // Splitter Catalog
    'reg_splitter': 'Splitter Catalog',
    'splitter_catalog_desc': 'Manage splitter types in the catalog.',
    'search_splitters': 'Search splitters...',
    'new_splitter': 'New Splitter',
    'edit_splitter': 'Edit Splitter',
    'add_splitter': 'Add Splitter',
    'splitter_name': 'Name',
    'splitter_ports': 'Ports',
    'splitter_type': 'Type',
    'splitter_mode': 'Mode',
    'splitter_mode_balanced': 'Balanced',
    'splitter_mode_unbalanced': 'Unbalanced',
    'splitter_in': 'In',
    'splitter_out': 'Out',
    'error_saving_splitter': 'Error saving splitter',

    // Pole Catalog
    'pole_catalog': 'Pole Catalog',
    'pole_catalog_desc': 'Manage available pole models.',
    'new_pole': 'New Pole',
    'pole_height': 'Height (m)',
    'pole_height_m': 'Height (m)',
    'pole_strength': 'Strength (daN)',
    'pole_strength_dan': 'Strength (daN)',
    'pole_shape': 'Shape',
    'actions': 'Actions',
    'shape_circular': 'Circular',
    'shape_duplot': 'Double T',
    'shape_square': 'Square',
    'concrete': 'Concrete',
    'wood': 'Wood',
    'metal': 'Metal',
    'fiber': 'Fiber',
    'attenuation_placeholder': 'e.g., 0.5',
    'equipment_name_placeholder': 'e.g., Huawei MA5608T, Cisco 2960...',
    'brand_placeholder': 'e.g., Furukawa, Prysmian...',
    'model_placeholder': 'e.g., AS-80, Drop Flat...',
    'confirm_delete': 'Are you sure?',
    'no_fusions_found': 'No fusions found.',
    'fusion_catalog_desc': 'Manage your standard fusion types and default attenuation values.',
    'new_fusion': 'New Fusion',
    'edit_fusion': 'Edit Fusion',
    'error_save_fusion': 'Error saving fusion',
    'error_delete_fusion': 'Error deleting fusion',
    'ctx_remove_cable': 'Remove Cable from Box',
    'ctx_edit_cable': 'Edit Cable',
    'ctx_next_box': 'Go to Next Box',
    'action_flip': 'Flip',
    'action_rotate': 'Rotate',
    'ctx_details': 'Details',
    'toast_select_next_box': 'Select the target box to navigate to',
    'error_cable_fully_connected': 'Cable is already fully connected',
    'loading': 'Loading...',
    'loading_diagram': 'Loading diagram...',
    'attenuation_help': 'For Unbalanced, describe the split ratio attenuation.',
    'attenuation_port1': 'Attenuation Port 1 (dB)',
    'attenuation_port2': 'Attenuation Port 2 (dB)',

    // Toasts
    'toast_imported': 'Imported {ctos} CTOs and {cables} Cables',
    'toast_cto_added': 'CTO added successfully',
    'toast_pop_added': 'POP added successfully',
    'toast_cto_splicing_saved': 'CTO Splicing saved',
    'toast_pop_saved': 'POP configuration saved',
    'toast_cto_deleted': 'CTO deleted successfully',
    'toast_pole_deleted': 'Pole deleted successfully',
    'toast_pole_added': 'Pole added successfully',
    'toast_pop_deleted': 'POP deleted',
    'toast_cable_updated': 'Cable updated',
    'toast_cable_deleted': 'Cable deleted successfully',
    'toast_cable_created': 'Cable created successfully',
    'toast_cable_connected_start': 'Cable start connected to {name}',
    'toast_cable_connected_end': 'Cable end connected to {name}',
    'toast_cable_anchored_pole': 'Cable anchored to pole {name}',
    'toast_cable_split': 'Cable split (Sangria) and connected to {name}',
    'import_error': 'Failed to import file. See console for details.',
    'import_no_geo': 'No compatible geometry (Points or Lines) found in this file.',
    'toast_mode_move_node': 'Move mode activated',
    'error_cto_duplicate_cable': 'This cable is already connected to this CTO.',
    'toast_auto_snap_success': 'Auto-connected/Split {count} locations within {distance}m.',
    'toast_poles_imported': '{count} poles imported successfully!',
    'toast_poles_import_error': 'Error importing poles.',
    'error_cable_endpoint_missing': 'Loose cable at other end',

    'toast_cable_disconnected': 'Cable disconnected',

    'otdr_title': 'OTDR Calculator',
    'otdr_distance_lbl': 'Distance (Meters)',
    'otdr_direction': 'Direction',
    'otdr_from_start': 'From Start/Node A',
    'otdr_from_end': 'From End/Node B',
    'otdr_locate': 'Locate Event',
    'otdr_result': 'Event Location',
    'otdr_error_length': 'Distance exceeds cable length ({length}m)',
    'otdr_trace_start_error': 'OTDR Trace: Please start from a cable fiber port.',
    'otdr_cable_not_found': 'OTDR Error: Cable not found.',
    'otdr_conn_mismatch': 'OTDR Error: Cable connectivity mismatch.',
    'otdr_end_open': 'OTDR: End of fiber reached (Open End).',
    'otdr_next_node_error': 'OTDR Error: Next node not found.',
    'otdr_fiber_end_node': 'OTDR: Fiber ends at {node} (Not Spliced).',
    'otdr_event_equipment': 'OTDR: Event at {node} (Equipment Connection).',
    'otdr_max_depth': 'OTDR: Max trace depth reached.',
    'otdr_success_cable': 'Located in cable {name}',
    'otdr_inside_cto': 'Inside CTO {name}',
    'otdr_trace_msg': 'Trace from selected fiber',
    'otdr_instruction_banner': 'Click a fiber port to measure distance.',
    'otdr_event_tooltip': 'OTDR Event',
    'otdr_traversing_pole': 'Traversing pole {name}...',

    // Common
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'confirm': 'Confirm',
    'edit': 'Edit',
    'edit_node_short': 'Edit',
    'move_node_short': 'Move',
    'delete_node_short': 'Delete',

    'name': 'Name',
    'status': 'Status',
    'type': 'Type',
    'copy_coordinates': 'Copy Coordinates',
    'open_google_maps': 'Open in Google Maps',
    'coordinates': 'Coordinates',
    'pinned_location': 'Save as',
    'viability_status': 'Viability Status',
    'viability_available': 'Service Available',
    'viability_unavailable': 'No Service',
    'distance_nearest': 'Dist. Nearest: {dist}m',
    'convert_to_cto': 'Convert to CTO',
    'convert_to_pole': 'Convert to Pole',
    'remove_pin': 'Remove Pin',
    'manage_splicing': 'Manage Splicing',
    'manage_pop': 'Manage Rack & Patching',
    'unsaved_changes': 'Unsaved Changes',
    'unsaved_changes_msg': 'You have unsaved changes. Do you want to save them before closing?',
    'discard': 'Discard',
    'save_and_close': 'Save & Close',
    'save_or_done': 'Save / Exit',
    'clear_connections_confirm': 'Are you sure you want to clear ALL connections? This cannot be undone.',
    'clear_all': 'Clear All',
    'confirm_delete_equip_msg': 'Are you sure you want to delete {name}?',
    'delete_warning_msg': 'Warning: All connections associated with this {type} will be removed permanently.',
    'changes_saved': 'Changes saved successfully',
    'position_saved': 'Position saved successfully!',
    'save_position': 'Save Position',
    'moving_node': 'Moving Element...',
    'editing_cable': 'Editing Cable...',
    'connecting_cable': 'Connecting Cables...',
    'finish': 'Finish',
    'finish_cable': 'Finish Cable',
    'connection_cancelled': 'Connection Cancelled',
    'meters': 'meters',
    'saved': 'Saved',
    'done': 'Done',

    // Statuses
    'status_PLANNED': 'Em projeto',
    'status_NOT_DEPLOYED': 'Não implantado',
    'status_DEPLOYED': 'Implantado',
    'status_CERTIFIED': 'Certificado',
    'status_ANALYSING': 'Em análise',
    'status_LICENSED': 'Licenciado',
    'pole_properties': 'Pole Properties',
    'select_pole': 'Select Pole',
    'search_pole': 'Search pole model...',
    'selection_pole_type': 'Pole Type',
    'pole_height_placeholder': 'Ex: 10',
    'confirm_delete_pole_msg': 'Are you sure you want to delete this pole?',

    // CTO/POP Details
    'edit_cto': 'Edit CTO',
    'edit_pop': 'Edit POP',
    'cto_info': 'CTO Information',
    'pop_info': 'POP Information',

    'connections': 'Connections',
    'spliced': 'Spliced',
    'patched': 'Patched',
    'splitters': 'Splitters',
    'equipment': 'Equipment',
    'backbone_cables': 'Backbone Cables',
    'confirm_delete_cto_msg': 'Confirm deletion of {name}? All connected cables will be removed.',
    'confirm_delete_pop_msg': 'Confirm deletion of POP {name}? This will remove all racks, equipment, and connected cables.',
    'delete_cto_btn': 'Delete CTO',
    'delete_pop_btn': 'Delete POP',

    // Cable Editor
    'edit_cable': 'Edit Cable',
    'cable_name': 'Cable Name',
    'fiber_count': 'Fiber Count',
    'unit_fibers': 'FIBERS',
    'unit_fiber_label': 'Fiber {n}',
    'loose_tubes': 'Loose Tubes',
    'tube': 'Tube',
    'technical_reserve': 'Technical Reserve',
    'geometric_length': 'Geometric Length',
    'estimated_length': 'Estimated Length',
    'toggle_reserve_label': 'Show Technical Reserve',
    'position_reserve_label': 'Position Reserve',
    'hide_reserve_label': 'Hide Technical Reserve',
    'tooltip_position_reserve': 'Click on map to position the technical reserve',
    'toast_reserve_positioned': 'Reserve positioned successfully',
    'map_color': 'Map Color',
    'disabled': 'Disabled',
    'confirm_delete_cable_msg': 'Confirm deletion of {name}? This will remove associated fusion splices.',
    'connect_cable': 'Connect Cable',
    'connect_to_box': 'Connect to Box',
    'delete_cable': 'Delete Cable',
    'color_standard': 'Color Standard',
    'standard_abnt': 'ABNT (Brazil)',
    'standard_eia': 'EIA-598-A (Intl)',
    'use_catalog_model': 'Use catalog model',
    'loading_catalog': 'Loading catalog...',
    'select_model': '-- Select a model --',
    'fiber_color_standard': 'Fiber Color Standard',
    'catalog_defined': 'Catalog Defined',
    'color_selection_info': 'Color defined by catalog according to status.',

    // Project Manager / Create Modal
    'project_manager': 'Project Manager',
    'create_project': 'Create Project',
    'new_project_placeholder': 'Project Name (e.g. Center Expansion)',
    'import_kmz_title': 'Import KMZ/KML to Current Project',
    'import_kmz_label': 'Import KMZ/KML',
    'import_kmz_desc': 'Clique to upload .kmz or .kml file',
    'processing': 'Processing...',
    'your_projects': 'Your Projects',
    'load_project': 'Load',
    'delete_last_project_error': 'Cannot delete the last project.',
    'confirm_delete_project': 'Delete project? This cannot be undone.',
    'active': 'Active',
    'items_count': 'Items: {ctos} CTOs, {cables} Cabos',
    'search_location': 'Initial Location',
    'search_location_placeholder': 'Search city or address...',
    'searching_location': 'Searching...',
    'no_location_results': 'No location found',

    'create_project_modal_title': 'Create New Project',
    'edit_project': 'Edit Project',
    'map_instruction': 'Drag the map or click to set the project center.',
    'confirm_create': 'Create Project',
    'snap_distance_lbl': 'Auto-Connect Distance (meters)',
    'snap_distance_help': 'Maximum distance for a cable to automatically snap to a box (CTO/POP) when dragging.',

    // CTO Internal Editor
    'splicing_title': '{name}',
    'dio_splicing_title': 'DIO Splicing: {name}',
    'splicing_help': 'Mouse Wheel to Zoom. Drag Background to Pan. Double-click points to remove.',

    'add_fusion': 'Fusion',
    'auto_splice': 'Auto Pass-Through',
    'auto_splice_help': 'Automated fiber splicing',
    'auto_splice_desc': 'Select two cables to connect all fibers sequentially (1 to 1, 2 to 2...).',
    'auto_splice_compatible': 'Fiber counts should ideally match for best results.',
    'select_cable': 'Select Cable...',
    'rotate_mode': 'Rotate Mode',
    'delete_mode': 'Delete Mode',
    'otdr_trace_tool': 'OTDR Trace',
    'snap_grid': 'Snap to Grid',
    'reset_connections': 'Reset Connections',
    'drop_to_connect': 'Drop on a port to connect, or background to disconnect.',
    'moving_point': 'Moving control point...',
    'panning': 'Panning',
    'general_help': 'Drag ports to connect. Click lines to add points. Double-click points to remove.',
    'rename_fusion': 'Rename Fusion Point:',
    'export_pdf': 'Export PDF',
    'generating_pdf': 'Generating...',
    'tool_vfl': 'VFL (Visual Fault Locator)',
    'vfl_active_msg': 'VFL Active: Click any port to inject light.',
    'vfl_active_status': 'VFL Active',
    'vfl_source_label': 'Source: {name}',
    'turn_off': 'Turn Off',
    'source_cable': 'Source Cable',
    'target_cable': 'Target Cable',
    'perform_splice': 'Fuse All Fibers',
    'splice_success': 'Successfully fused {count} fibers.',
    'smart_align': 'Smart Align',
    'select_splitter': 'Select Splitter',
    'select_fusion_type': 'Select Fusion Type',
    'fusion_tool_active': 'Fusion Mode: Click to add fusion point',

    // DIO Editor Strings
    'link_cables': 'Link Cables',
    'no_available_fusions': 'No fusion types registered',
    'linked_pole': 'Linked Pole',
    'link_to_nearest_pole': 'Link to nearest pole',
    'linked_cables': 'Linked Cables',
    'link_to_nearest_cables': 'Link nearest cables',
    'unlinked': 'Unlinked',
    'link_cables_help': 'You can link cables to this DIO using the button above.',
    'connect_fiber_tray': 'Connect Fiber to DIO Tray',
    'connected_to_port': 'Currently connected to Port {port}',
    'select_tray_port_help': 'Select a tray port below to splice this fiber.',
    'green_light_help': 'Green lights indicate active OLT signal flowing to the cable.',
    'select_target_port_dio': 'Select a Target Port on {name}',
    'currently_connected': 'Currently Connected',
    'port_occupied_splice': 'Port occupied by another splice',
    'port_has_patch_cord': 'Port has patch cord (Splice allowed)',
    'port_available': 'Available',
    'linked_to_dio': 'Linked to {name}',
    'legend_active_signal': 'Active Signal',
    'legend_vfl_source': 'VFL Source',
    'unit_meters': 'METERS',
    'click_to_manage': 'Click to Manage',
    'click_to_connect': 'Click to Connect',
    'splice_trays': 'Splice Trays',

    'tray': 'Tray',
    'trays': 'Trays',

    // Box Catalog
    'box_catalog': 'Box Catalog',
    'box_catalog_desc': 'Manage available box models (CTO/CEO).',
    'confirm_delete_title': 'Confirm Deletion',
    'confirm_delete_message': 'Are you sure you want to delete this item? This action cannot be undone.',
    'no_results': 'No results found',
    'name_placeholder': 'e.g., CTO-PRECON',
    'box_model': 'Box Model',
    'select_box_model': 'Select Model...',
    'reserve_loop_length': 'Tech. Reserve',
    'reserve': 'Reserve',
    'brand': 'Brand',
    'model': 'Model',
    'ident_color': 'Color',
    'type_cto_termination': 'CTO (Termination)',
    'type_ceo_splice': 'CEO (Splice)',
    'edit_box': 'Edit Box',
    'new_box': 'New Box',
    'search_placeholder_box': 'Search by name, brand or model...',
    'add_new': 'Add New',
    'details_placeholder': 'Additional details...',
    'bm_cancel': 'Cancel',


    // POP Editor
    'pop_editor_title': 'POP Management: {name}',
    'add_dio': 'Add DIO',
    'add_active_equipment': 'Add Active',
    'olt_ports': 'PON Ports',
    'active_ports': 'Ports',
    'dio_ports': 'Ports',
    'rack_view': 'Rack View',

    // OLT/DIO Modal
    'modal_add_olt_title': 'Add Active Equipment',
    'modal_edit_olt_title': 'Edit Active Equipment',
    'modal_add_dio_title': 'Add Passive Equipment (DIO)',
    'modal_edit_dio_title': 'Edit DIO',
    'equipment_type': 'Equipment Type',
    'type_olt': 'OLT (GPON)',
    'type_switch': 'Switch',
    'type_router': 'Router',
    'type_server': 'Server',
    'type_other': 'Other',
    'custom_configuration': 'Custom Configuration',
    'catalog_label': 'Catalog',
    'chassis_config': 'Chassis Configuration',
    'total_slots': 'Total Slots',
    'preview': 'Preview',
    'olt_preview_msg': 'This will create a {total} port OLT ({slots} slots × {ports} ports).',
    'olt_config_locked_msg': 'Chassis capacity managed via Catalog.',
    'create_device': 'Create Device',
    'specifications': 'Specifications',
    'dio_preview_msg': 'Creates a Rack-mountable DIO with {ports} splice capacity organized in {trays} trays.',
    'ports_label': 'Ports',
    'capacity_label': 'Capacity',
    'dio_capacity_warning': 'Reducing capacity will permanently delete connections on removed ports.',
    'n_ports': '{n} Ports',
    'manage_slots': 'Manage Slots',
    'slot_active': 'Active',
    'slot_empty': 'Empty',
    'port_count': 'Ports',
    'add_card': 'Add Card',
    'slot_label': 'Slot {n}',
    'type_change_warning': 'Changing the equipment type may reset the port structure and remove existing connections.',
    'type_locked': 'Equipment type locked to maintain structure integrity.',
    'connection_slot_port': 'Connection for Slot/Port',
    'select_dio_port': 'Select DIO Port',
    'connected': 'Connected',
    'not_connected': 'Not Connected',
    'disconnect': 'Disconnect',
    'save_changes': 'Save Changes',

    'role_owner': 'Owner',

    'error_target_not_found': 'Target not found',
    'toast_select_next_cable': 'Select another cable to connect',
    'password': 'Password',
    'edit_user': 'Edit User',
    'update': 'Update',
    'confirm_delete_user_msg': 'Are you sure you want to delete user {username} ({email})?',
    'create': 'Create',

    // User Management Errors
    'error_username_taken': 'Username or email is already taken.',
    'error_email_taken': 'Email is already taken.',
    'error_password_length': 'Password must be at least 6 characters long.',
    'error_cannot_delete_self': 'You cannot delete your own account.',
    'error_generic': 'An unexpected error occurred.',
    'error_create_user': 'Failed to create user.',
    'error_delete_user': 'Failed to delete user.',
    'error_email_required': 'Email is required.',

    // --- LANDING PAGE ---
    'landing_features': 'Features',
    'landing_performance': 'Performance',
    'landing_pricing': 'Pricing',
    'landing_how_it_works': 'How it Works',
    'landing_login': 'Log in',
    'landing_get_started': 'Get Started',
    'landing_hero_badge': 'New Generation Platform',
    'landing_hero_title_1': 'The Ultimate',
    'landing_hero_title_2': 'FTTx Network',
    'landing_hero_title_3': 'Management Platform',
    'landing_hero_desc': 'Design, document, and manage your fiber network with high-performance interactive maps. Built for ISPs who demand precision and scalability.',
    'landing_start_trial': 'Start Free Trial',
    'landing_live_demo': 'See Live Demo',
    'demo_modal_title': 'Demonstration',
    'demo_modal_subtitle': 'FTTx Planner Pro',
    'demo_modal_no_videos': 'No videos available.',
    'demo_modal_footer': 'Select a video to watch',
    'demo_modal_cta': 'Talk to Consultant',
    'demo_modal_select_msg': 'Select a video to watch',
    'landing_map_engine': 'Map Engine',
    'landing_leaflet': 'Leaflet Powered',

    'landing_problem_title': 'Stop Managing Networks with',
    'landing_problem_highlight': 'Spreadsheets',
    'landing_problem_desc': 'Traditional methods like Google Earth + Excel are prone to errors, lack real-time updates, and become unmanageable as your network grows. You need a system that understands fiber optics, signal loss, and topology.',
    'landing_problem_1': 'No visibility into available ports',
    'landing_problem_2': 'Manual documentation is always outdated',
    'landing_problem_3': 'Hard to track signal loss and fusion points',
    'landing_problem_4': 'Team collaboration is a nightmare',
    'landing_error_connection': 'Error: Connection limit exceeded',

    'landing_features_title': 'Everything You Need to Scale',
    'landing_features_desc': 'From planning to deployment, our tool covers every aspect of your ISP operation.',
    'landing_feat_maps': 'Interactive Maps',
    'landing_feat_maps_desc': 'Visualize your entire network on high-performance maps. Zoom, pan, and edit with precision.',
    'landing_feat_cable': 'Cable & Fusion Management',
    'landing_feat_cable_desc': 'Track every fiber strand, fusion splice, and splitter connection. Auto-calculate signal loss.',
    'landing_feat_team': 'Multi-Tenant & Teams',
    'landing_feat_team_desc': 'Manage multiple projects and assign role-based access control to your engineering team.',
    'landing_feat_snap': 'Auto-Snap & Design Tools',
    'landing_feat_snap_desc': 'Smart drawing tools that snap to existing infrastructure, speeding up your design process by 50%.',
    'landing_feat_bom': 'Inventory & Reports',
    'landing_feat_bom_desc': 'Generate BOM (Bill of Materials) automatically. Know exactly how much cable you need.',
    'landing_feat_import': 'Import/Export',
    'landing_feat_import_desc': 'Seamlessly import KMZ/KML files from Google Earth and export your projects for field teams.',

    'landing_perf_badge': 'Ultra Performance',
    'landing_perf_title': 'Built for Millions of Elements',
    'landing_perf_desc': "Don't let lag slow you down. Our engine is optimized for browsing massive networks with zero latency. Handle city-wide deployments with thousands of CTOs and POPs seamlessly.",
    'landing_stat_elements': 'Elements rendered',
    'landing_stat_scroll': 'Smooth scroll',
    'landing_stat_search': 'Search time',
    'landing_stat_uptime': 'Uptime',
    'landing_graph_engine': 'Rendering Engine',
    'landing_graph_active': 'Active',
    'landing_graph_load': 'System Load: 5%',

    'landing_sec_title': 'Enterprise-Grade Security',
    'landing_sec_desc': 'Your network data is your most valuable asset. We treat it with the protection it deserves.',
    'landing_sec_1': 'End-to-End Encryption',
    'landing_sec_2': 'Daily Backups',
    'landing_sec_3': 'Role-Based Access',
    'landing_sec_4': 'Audit Logs',
    'landing_sec_5': '99.9% SLA',

    'landing_steps_title': 'Start in 3 Simple Steps',
    'landing_step_1_title': 'Create Workspace',
    'landing_step_1_desc': 'Sign up and create your first project area in seconds.',
    'landing_step_2_title': 'Design or Import',
    'landing_step_2_desc': 'Draw your network or import existing KMZ files instantly.',
    'landing_step_3_title': 'Manage & Scale',
    'landing_step_3_desc': 'Invite your team and start managing operations.',

    'landing_cta_title': 'Ready to modernize your ISP?',
    'landing_cta_desc': 'Join hundreds of network engineers who trust FTTx Planner for their daily operations.',
    'landing_cta_btn': 'Get Started for Free',

    'landing_footer_desc': 'The professional standard for FTTx network design and management.',
    'landing_footer_product': 'Product',
    'landing_footer_company': 'Company',
    'landing_footer_legal': 'Legal',
    'landing_footer_rights': '© 2024 FTTx Planner. All rights reserved.',

    // Pricing
    'pricing_title': 'Simple, Transparent Pricing',
    'pricing_desc': 'Choose the perfect plan for your ISP growth stage. No hidden fees.',
    'plan_free': 'Free',
    'plan_basic': 'Basic',
    'plan_inter': 'Intermediate',
    'plan_unlimited': 'Unlimited',
    'price_free': 'Free',
    'month': '/month',
    'feature_projects': '{count} Projects',
    'feature_users': '{count} Users',
    'feature_ctos': '{count} CTOs',
    'feature_pops': '{count} POPs',
    'feature_unlimited': 'Unlimited',
    'plan_cta': 'Get Started',
    'most_popular': 'Most Popular',
    'feature_1_project': '1 Project',
    'feature_1_user': '1 User',
    'feature_basic_maps': 'Basic Maps',
    'feature_5_projects': '5 Projects',
    'feature_3_users': '3 Users',
    'feature_email_support': 'Email Support',
    'feature_unlimited_all': 'Unlimited Everything',
    'feature_priority_support': 'Priority Support',
    'feature_auto_backup': 'Automatic Backup',
    'feature_projects_unlimited': 'Unlimited Projects',
    'feature_users_unlimited': 'Unlimited Users',
    'feature_ctos_unlimited': 'Unlimited CTOs',

    // Backup
    'backup_title': 'Backup Manager',
    'backup_desc': 'Manage your system backups. Daily backups are performed automatically at 02:00 AM.',
    'create_backup': 'Create Backup',
    'backup_filename': 'Filename',
    'backup_date': 'Date',
    'backup_size': 'Size',
    'download': 'Download',
    'confirm_delete_backup': 'Are you sure you want to delete this backup?',
    'backup_success': 'Backup created successfully',
    'backup_created_at': 'Created At',
    'backup_manual': 'Manual',

    'backup_auto': 'Automatic',
    'no_backups': 'No backups found.',
    'restore': 'Restore',
    'upload_restore': 'Upload & Restore',
    'restore_confirm': 'WARNING: This will delete ALL current network data (CTOs, Cables, POPs, Projects) and replace it with the backup. This cannot be undone. Are you sure?',
    'restore_success': 'System restored successfully. Reloading...',
    'pon': 'PON',
    'slot': 'Slot',
    'properties': 'Properties',
    'cancel_subscription': 'Cancel Subscription',
    'cancel_subscription_confirm': 'Are you sure you want to cancel? You will lose access to premium features at the end of the billing period.',
    'cancel_subscription_success': 'Subscription canceled successfully.',
    'cancel_subscription_error': 'Failed to cancel subscription. Please try again or contact support.',
    'cancel_subscription_disclaimer': 'By canceling, you retain access until the end of original billing cycle.',
    'upgrade_plan': 'Upgrade Plan',
    'upgrade_disclaimer': 'Check available plans to upgrade your account.',
    'maximize': 'Maximize',
    'mode_ruler': 'Ruler',
    'tooltip_ruler': 'Ruler Tool: Click on map to measure distance between points.',
    'ruler_clear': 'Clear Ruler',
    'ruler_total': 'Total Distance',
    'admin_col_phone': 'Phone',
    'admin_col_infrastructure': 'Infrastructure',
    'admin_col_created': 'Created',
    'admin_col_last_access': 'Last Access',
    'admin_never': 'Never',
    'admin_no_phone': 'No phone',

    // Report / Network Analysis
    'report_title': 'Project Report',
    'report_analyze': 'Network Analysis',
    'report_summary': 'Summary',
    'report_infrastructure': 'Infrastructure',
    'report_cables': 'Cables & Fibers',
    'report_qty': 'Qty',
    'report_total_ctos': 'Total CTOs',
    'report_total_ceos': 'Total CEOs (Splice Boxes)',
    'report_total_pops': 'Total POPs',
    'report_total_poles': 'Total Poles',
    'report_cable_type': 'Fiber Type',
    'report_cable_count_active': 'Active Cables',
    'report_total_meters': 'Total Meters',
    'report_total_meters_active': 'Total Deployment (m)',
    'report_total_meters_planned': 'Total Planned (m)',
    'report_no_data': 'No data available for analysis.',
    'report_export_csv': 'Export CSV',
    'report_estimated': 'Estimated',
    'email_admin_new_client_subject': 'New Client Registered: {company}',
    'email_admin_new_client_body': 'A new client has registered in the system.<br><br><b>Details:</b><br><ul><li><b>Username:</b> {username}</li><li><b>Company:</b> {company}</li><li><b>Email:</b> {email}</li><li><b>Phone:</b> {phone}</li><li><b>Plan:</b> {plan}</li><li><b>Source:</b> {source}</li></ul>',

    // Optical Power Modal
    'optical_budget': 'Optical Budget',
    'optical_path_for': 'Optical path for',
    'no_signal': 'No Signal (Disconnected)',
    'final_power': 'Final Power',
    'status_ok': 'OK (Ideal)',
    'status_marginal': 'Marginal (Warning)',
    'status_fail': 'Fail (Critical)',
    'origin_olt': 'Origin (OLT)',
    'output_power_short': 'Output Power',
    'total_loss': 'Total Loss',
    'path_elements': 'Path elements',
    'path_details': 'Path Details',
    'type_CABLE': 'Cable',
    'type_SPLITTER': 'Splitter',
    'type_FUSION': 'Fusion',
    'type_CONNECTOR': 'Connector / DIO',
    'type_OLT': 'OLT',

    // Map Layers
    'map_street': 'Map',
    'map_satellite': 'Satellite',
    'map_layers': 'Layers',
    'layer_cables': 'Cables',
    'layer_ctos': 'CTOs',
    'layer_pops': 'POPs',
    'layer_customers': 'Customers',

    // Customers
    'customer_title': 'Customers',
    'add_customer': 'Add Customer',
    'customer_name': 'Name',
    'draw_drop_instruction': 'Draw drop cable to a CTO',
    'select_cto_drop': 'Drop cable on CTO to connect',
    'connect_customer_title': 'Connect Customer',
    'select_splitter_port': 'Select Splitter Port',
    'cancel_drop': 'Cancel Drop',
    'drop_saved': 'Drop cable saved successfully',
    'customer_doc': 'Document (CPF/CNPJ)',
    'customer_phone': 'Phone',
    'customer_address': 'Address',
    'customer_connection': 'Connection',
    'select_cto': 'Select CTO',
    'select_port': 'Select Port',
    'customer_status_title': 'Status',
    'customer_status_active': 'Active',
    'customer_status_inactive': 'Inactive',
    'customer_status_planned': 'Planned',
    'onu_details': 'ONU Details',
    'onu_serial': 'Serial Number',
    'onu_mac': 'MAC Address',
    'pppoe_service': 'PPPoE Service',
    'no_connection_found': 'No drop connection found for this customer.',
    'connected_cto': 'Connected CTO',
    'no_ctos_near': 'No nearby CTOs found.',
    'port_free': 'Free',
    'port_occupied': 'Occupied',
    'save_customer': 'Save Customer',
    'saving': 'Saving...',
    'customer_port_tooltip': 'Customer: {name}',
    'port_label': 'Port {number}',
    'view_diagram': 'View Diagram',
    'delete_customer': 'Delete Customer',
    'confirm_delete_customer': 'Are you sure you want to delete this customer?',
    'customer_saved': 'Customer saved successfully',
    'customer_deleted': 'Customer deleted successfully',
    'customer_modal_title': 'Customer Registration',
    'customer_data': 'Data',
    'tooltip_add_customer': 'Placement Mode: Click on map to add a Customer.',
    'mode_add_customer': 'Place Customer',
    'sidebar_add_customer': 'New Customer',
    'no_splitters_in_cto': 'No splitters in this CTO.',
    'port_occupied_by': 'Occupied by: {name}',
    'port_selected': 'Selected',
    'error_save_customer': 'Error saving customer.',
    'change': 'Change',
    'select_splitter': 'Select Splitter',
    'splitter_blocked_desc': 'This splitter does not allow customer connections',
    'connector_blocked': 'Blocked',
    'onu_data_section': 'ONU / Connection Data',
    'pppoe_user': 'PPPoE User',
    'onu_power': 'ONU Power (dBm)',
    'drop_length': 'Drop Length',
    'meters_abbrev': 'm',
    'draw_customer_drop': 'Draw Customer Drop',
    'draw_customer_drop_desc': 'Click to start drawing the drop cable on the map.',
    'draw_drop': 'Draw',
    'confirm_disconnect': 'Are you sure you want to disconnect this customer? This will remove the drop cable and connection.',
    'disconnect': 'Disconnect',
    'reposition_customer': 'Reposition Customer',
    'reposition_customer_instruction': 'Click on the new location for the customer',
    'repositioning': 'Repositioning...',
    'search_existing_customer': 'Search existing customer...',
    'no_customers_found': 'No customers found.',
    'connect_customer_title': 'Connect Customer',
    'connect_customer_desc': 'Select a port to finalize connection',
    'target_cto': 'Target CTO',
    'no_splitters_found_error': 'No splitters found. Connection requires splitter installation.',
    'ports_total': '{count} Ports Total',
    'select_free_port': 'Select a free port to continue.',
    'selected_port_info': 'Selected: Port {port}',


    // Pole Catalog
    'pole_catalog': 'Pole Catalog',
    'pole_catalog_desc': 'Manage available pole types.',
    'new_pole': 'New Pole',
    'edit_pole': 'Edit Pole',
    'pole_shape': 'Shape',
    'shape_circular': 'Circular',
    'shape_duplot': 'Double T',
    'shape_square': 'Square',
    'pole_height': 'Height',
    'pole_strength': 'Strength',
    'concrete': 'Concrete',
    'wood': 'Wood',
    'metal': 'Metal',
    'fiber': 'Fiber',

    // Box Catalog
    'box_catalog': 'Box Catalog',
    'box_catalog_desc': 'Manage splice box and CTO models.',
    'new_box': 'New Box',
    'edit_box': 'Edit Box',
    'type_cto_termination': 'CTO (Termination)',
    'type_ceo_splice': 'CEO (Splice)',
    'reserve_loop_length': 'Technical Reserve',
    'ident_color': 'Identification Color',

    // Cable Catalog
    'cable_catalog': 'Cable Catalog',
    'cable_catalog_desc': 'Manage fiber optic cable types.',
    'new_cable': 'New Cable',
    'edit_cable': 'Edit Cable',
    'search_placeholder_cable': 'Search cables...',
    'fiber_count': 'Fiber Count',
    'loose_tubes': 'Loose Tubes',
    'fibers_per_tube': 'Fibers per Tube',
    'attenuation_db': 'Attenuation (dB)',
    'fiber_color_standard': 'Color Standard',
    'standard_abnt': 'ABNT',
    'standard_eia': 'EIA/TIA',
    'unit_fiber_label': 'Fiber {n}',
    'specifications': 'Specifications',

    // Active Equipment (OLT)
    'reg_active_equipment': 'Active Equipment',
    'olt_catalog_desc': 'Manage OLTs, Switches and other equipment.',
    'modal_add_olt_title': 'Add Equipment',
    'modal_edit_olt_title': 'Edit Equipment',
    'equipment_name': 'Equipment Name',
    'equipment_name_placeholder': 'Ex: Huawei MA5608T...',
    'type_olt': 'OLT',
    'type_switch': 'Switch',
    'type_router': 'Router',
    'type_server': 'Server',
    'type_other': 'Other',
    'output_power': 'Output Power',
    'power_consumption': 'Consumption',
    'olt_slots': 'Slots',
    'olt_ports': 'PON Ports',
    'active_ports': 'Ports',
    'ports_per_slot': 'Ports per Slot',
    'olt_output_power_help': 'Average power per port in dBm',
    'error_saving_olt': 'Error saving equipment.',

    // Fusion Catalog
    'reg_fusao': 'Fusion Types',
    'fusion_catalog_desc': 'Manage fusion/connection loss types.',
    'new_fusion': 'New Fusion',
    'edit_fusion': 'Edit Fusion',
    'error_save_fusion': 'Error saving fusion',
    'error_delete_fusion': 'Error deleting fusion',
    'no_fusions_found': 'No fusions found',
    'attenuation': 'Attenuation',

    // Customer Registration
    'manage_customers_desc': 'Manage customer base and connections.',
  },
  pt: {
    'upgrade_plan': 'Fazer Upgrade',
    'upgrade_disclaimer': 'Confira os planos disponíveis para turbinar sua conta.',
    'cancel_subscription': 'Cancelar Assinatura',
    'cancel_subscription_confirm': 'Tem certeza que deseja cancelar? Você perderá o acesso aos recursos premium no fim do período de faturamento.',
    'cancel_subscription_success': 'Assinatura cancelada com sucesso.',
    'cancel_subscription_error': 'Erro ao cancelar assinatura. Tente novamente ou contate o suporte.',
    'cancel_subscription_disclaimer': 'Ao cancelar, você mantém o acesso até o fim do ciclo atual de faturamento.',
    // Theme
    'theme_light': 'Modo Claro',
    'theme_dark': 'Modo Escuro',

    // --- LANDING PAGE ---
    'landing_features': 'Recursos',
    'landing_performance': 'Performance',
    'landing_pricing': 'Planos',
    'landing_how_it_works': 'Como Funciona',
    'landing_login': 'Entrar',
    'landing_get_started': 'Começar',
    'landing_hero_badge': 'Nova Geração',
    'landing_hero_title_1': 'A Plataforma Definitiva',
    'landing_hero_title_2': 'de Rede FTTx',
    'landing_hero_title_3': 'Gestão e Projetos',
    'landing_hero_desc': 'Projete, documente e gerencie sua rede de fibra com mapas interativos de alta performance. Feito para provedores que exigem precisão e escala.',
    'landing_start_trial': 'Teste Grátis',
    'landing_live_demo': 'Ver Live Demo',
    'demo_modal_title': 'Demonstração',
    'demo_modal_subtitle': 'FTTx Planner Pro',
    'demo_modal_no_videos': 'Nenhum vídeo disponível.',
    'demo_modal_footer': 'Selecione um vídeo para assistir',
    'demo_modal_cta': 'Falar com Consultor',
    'demo_modal_select_msg': 'Selecione um vídeo para assistir',
    'landing_map_engine': 'Motor de Mapa',
    'landing_leaflet': 'Tecnologia Leaflet',

    'landing_problem_title': 'Pare de Gerenciar Redes com',
    'landing_problem_highlight': 'Planilhas',
    'landing_problem_desc': 'Métodos tradicionais como Google Earth + Excel são propensos a erros, não atualizam em tempo real e ficam incontroláveis quando a rede cresce. Você precisa de um sistema que entenda fibra óptica, perda de sinal e topologia.',
    'landing_problem_1': 'Sem visibilidade de portas livres',
    'landing_problem_2': 'Documentação manual sempre desatualizada',
    'landing_problem_3': 'Difícil rastrear perda de sinal e fusões',
    'landing_problem_4': 'Colaboração em equipe é um pesadelo',
    'landing_error_connection': 'Erro: Limite de conexões excedido',

    'landing_features_title': 'Tudo Que Você Precisa para Escalar',
    'landing_features_desc': 'Do planejamento à implantação, nossa ferramenta cobre cada aspecto da sua operação ISP.',
    'landing_feat_maps': 'Mapas Interativos',
    'landing_feat_maps_desc': 'Visualize toda sua rede em mapas de alta performance. Zoom, pan e edições com precisão.',
    'landing_feat_cable': 'Gestão de Cabos e Fusões',
    'landing_feat_cable_desc': 'Rastreie cada fibra, fusão e conexão de splitter. Cálculo automático de perda de sinal.',
    'landing_feat_team': 'Multi-Tenant e Equipes',
    'landing_feat_team_desc': 'Gerencie múltiplos projetos e atribua controle de acesso baseado em cargos para seu time de engenharia.',
    'landing_feat_snap': 'Ferramentas de Design Inteligente',
    'landing_feat_snap_desc': 'Ferramentas de desenho que "grudam" na infraestrutura existente, acelerando seu processo de design em 50%.',
    'landing_feat_bom': 'Inventário e Relatórios',
    'landing_feat_bom_desc': 'Gere BOM (Lista de Materiais) automaticamente. Saiba exatamente quanto de cabo você precisa.',
    'landing_feat_import': 'Importação/Exportação',
    'landing_feat_import_desc': 'Importe arquivos KMZ/KML do Google Earth sem problemas e exporte projetos para equipes de campo.',

    'landing_perf_badge': 'Ultra Performance',
    'landing_perf_title': 'Feito para Milhões de Elementos',
    'landing_perf_desc': "Não deixe o lag te atrasar. Nosso motor é otimizado para navegar em redes massivas com zero latência. Lide com implantações em cidades inteiras com milhares de CTOs e POPs sem problemas.",
    'landing_stat_elements': 'Elementos renderizados',
    'landing_stat_scroll': 'Rolagem suave',
    'landing_stat_search': 'Tempo de busca',
    'landing_stat_uptime': 'Disponibilidade',
    'landing_graph_engine': 'Motor de Renderização',
    'landing_graph_active': 'Ativo',
    'landing_graph_load': 'Carga do Sistema: 5%',

    'landing_sec_title': 'Segurança de Nível Empresarial',
    'landing_sec_desc': 'Seus dados de rede são seu ativo mais valioso. Nós tratamos com a proteção que merecem.',
    'landing_sec_1': 'Criptografia Ponta-a-Ponta',
    'landing_sec_2': 'Backups Diários',
    'landing_sec_3': 'Controle de Acesso por Cargo',
    'landing_sec_4': 'Logs de Auditoria',
    'landing_sec_5': 'SLA de 99.9%',

    'landing_steps_title': 'Comece em 3 Passos Simples',
    'landing_step_1_title': 'Crie seu Workspace',
    'landing_step_1_desc': 'Cadastre-se e crie sua primeira área de projeto em segundos.',
    'landing_step_2_title': 'Desenhe ou Importe',
    'landing_step_2_desc': 'Desenhe sua rede do zero ou importe arquivos KMZ existentes instantaneamente.',
    'landing_step_3_title': 'Gerencie e Escale',
    'landing_step_3_desc': 'Convide seu time e comece a gerenciar as operações.',

    'landing_cta_title': 'Pronto para modernizar seu ISP?',
    'landing_cta_desc': 'Junte-se a centenas de engenheiros de rede que confiam no FTTx Planner para suas operações diárias.',
    'landing_cta_btn': 'Começar Grátis',

    'landing_footer_desc': 'O padrão profissional para design e gestão de redes FTTx.',
    'landing_footer_product': 'Produto',
    'landing_footer_company': 'Empresa',
    'landing_footer_legal': 'Legal',
    'landing_footer_rights': '© 2024 FTTx Planner. Todos os direitos reservados.',

    // Pricing
    'pricing_title': 'Planos Simples e Transparentes',
    'pricing_desc': 'Escolha o plano ideal para o estágio de crescimento do seu provedor.',
    'plan_free': 'Grátis',
    'plan_basic': 'Básico',
    'plan_inter': 'Intermediário',
    'plan_unlimited': 'Ilimitado',
    'price_free': 'Grátis',
    'month': '/mês',
    'feature_projects': '{count} Projetos',
    'feature_users': '{count} Usuários',
    'feature_ctos': '{count} CTOs',
    'feature_pops': '{count} POPs',
    'feature_unlimited': 'Ilimitado',
    'plan_cta': 'Começar Agora',
    'most_popular': 'Mais Popular',
    'feature_1_project': '1 Projeto',
    'feature_1_user': '1 Usuário',
    'copy_coordinates': 'Copiar Coordenadas',
    'open_google_maps': 'Abrir no Google Maps',
    'coordinates': 'Coordenadas',
    'pinned_location': 'Salvar como',
    'viability_status': 'Viabilidade',
    'viability_available': 'Viabilidade Disponível',
    'viability_unavailable': 'Sem Viabilidade',
    'distance_nearest': 'Dist. Aproximada: {dist}m',
    'convert_to_cto': 'Salvar como Caixa',
    'convert_to_pole': 'Salvar como Poste',
    'remove_pin': 'Remover Pin',
    'feature_basic_maps': 'Mapas Básicos',
    'feature_5_projects': '5 Projetos',
    'feature_3_users': '3 Usuários',
    'feature_email_support': 'Suporte por Email',
    'feature_unlimited_all': 'Tudo Ilimitado',
    'feature_priority_support': 'Suporte Prioritário',
    'feature_auto_backup': 'Backup Automático',
    'feature_projects_unlimited': 'Projetos Ilimitados',
    'feature_users_unlimited': 'Usuários Ilimitados',
    'feature_ctos_unlimited': 'CTOs Ilimitados',

    // Login & Dashboard
    'enter_btn': 'Entrar no Sistema',
    'login_title': 'FTTx Planner',
    'login_subtitle': 'Entre com suas credenciais',
    'login_email_placeholder': 'Email',
    'login_password_placeholder': 'Senha',
    'login_button_loading': 'Entrando...',
    'login_button': 'Entrar',
    'login_create_account': 'Criar nova conta',
    'forgot_password': 'Esqueci minha senha',
    'forgot_password_title': 'Recuperar Senha',
    'forgot_password_subtitle': 'Digite seu e-mail para receber um link de recuperação.',
    'forgot_password_send': 'Enviar Link de Recuperação',
    'forgot_password_success': 'E-mail enviado! Verifique sua caixa de entrada.',
    'forgot_password_error_generic': 'Erro ao enviar e-mail',
    'forgot_password_error_connection': 'Erro de conexão com o servidor',
    'reset_password_title': 'Nova Senha',
    'reset_password_subtitle': 'Digite sua nova senha abaixo.',
    'reset_password_button': 'Redefinir Senha',
    'reset_password_success': 'Senha alterada com sucesso!',
    'reset_password_error': 'Token inválido ou expirado.',
    'reset_password_error_mismatch': 'As senhas não coincidem.',
    'reset_password_error_length': 'A senha deve ter pelo menos 6 caracteres.',
    'reset_password_error_connection': 'Erro de conexão com o servidor',
    'reset_password_success_redirect': 'Sua nova senha foi salva! Redirecionando...',
    'login_feature_label': 'Destaque',
    'login_feature_title': 'Editor de Fusão',
    'back_to_home': 'Voltar ao Início',
    'company_settings_title': 'Configurações da Empresa',
    'company_settings_subtitle': 'Gerencie a identidade e informações de contato da sua empresa',
    'company_name_label': 'Nome da Empresa',
    'company_logo_label': 'Logo da Empresa',
    'company_logo_hint': 'Recomendado: Imagem quadrada, PNG ou JPG',
    'company_cnpj_label': 'CNPJ',
    'company_phone_label': 'Telefone de Contato',
    'company_email_label': 'E-mail Comercial',
    'company_website_label': 'Website',
    'company_address_label': 'Endereço',
    'company_city_label': 'Cidade',
    'company_state_label': 'Estado',
    'company_zip_label': 'CEP',
    'company_save_button': 'Salvar Configurações',
    'company_save_success': 'Configurações da empresa atualizadas com sucesso!',
    'company_save_error': 'Falha ao atualizar configurações da empresa',
    'company_upload_logo': 'Enviar Logo',
    'company_uploading': 'Enviando...',
    'register_page_title': 'Criar Conta FTTx Planner',
    'register_subtitle': 'Junte-se ao FTTx Planner',
    'register_company_placeholder': 'Nome da Empresa (Provedor)',
    'register_phone_placeholder': 'Telefone de Contato',
    'register_password_placeholder': 'Senha',
    'register_confirm_password_placeholder': 'Confirmar Senha',
    'register_button': 'Registrar Conta',
    'register_already_have_account': 'Já tem uma conta? Entrar',
    'register_error_empty': 'Por favor, preencha todos os campos.',
    'register_error_match': 'As senhas não coincidem.',
    'register_btn': 'Criar Conta',
    'no_account': 'Não tem uma conta?',
    'already_have_account': 'Já tem uma conta?',
    'register_title': 'Criar Conta FTTx Planner',
    'back_to_login': 'Voltar para o Login',
    'registration_success': 'Conta criada! Agora você pode entrar.',
    'registration_failed': 'Falha no registro. Usuário já pode existir.',
    'welcome': 'Bem-vindo, {name}',
    'logout': 'Sair',
    'my_projects': 'Meus Projetos',
    'create_new_project_btn': 'Criar Novo Projeto',
    'no_projects': 'Nenhum projeto encontrado. Crie o primeiro!',
    'last_modified': 'Última modificação: {date}',
    'open_project': 'Abrir Projeto',
    'exit_project': 'Sair para o Painel',
    'delete_project_confirm': 'Tem certeza que deseja deletar o projeto "{name}"?',
    'project_updated': 'Projeto atualizado com sucesso!',
    'toast_project_deleted': 'Projeto excluído com sucesso!',
    'error_project_update': 'Falha ao atualizar projeto.',
    'error_project_delete': 'Falha ao excluir projeto.',
    'error_saving_changes': 'Erro ao salvar as alterações. Tente novamente.',

    // App / Sidebar
    'app_title': 'Planejador FTTx',
    'active_project': 'Projeto Ativo',
    'tools': 'Ferramentas',
    'settings': 'Configurações',
    'system_settings': 'Configurações',
    'view_options': 'Opções de Visualização',
    'zoom_in': 'Aproximar',
    'zoom_out': 'Afastar',
    'center_view': 'Centralizar Vista',
    'show_all': 'Mostrar Todos os Itens',
    'toggle_labels': 'Nomes',
    'sidebar_collapse': 'Recolher Menu',
    'sidebar_expand': 'Expandir Menu',
    'menu': 'Menu',
    'home': 'Início',
    'mode_view': 'Seleção / Nav',
    'mode_move': 'Mover Elementos',
    'mode_otdr': 'OTDR Trace',
    'sidebar_pole': 'Poste',
    'mode_add_cto': 'Adicionar CTO',
    'mode_add_pop': 'Adicionar POP',
    'mode_draw_cable': 'Desenhar Cabo',
    'mode_connect_cable': 'Conectar / Sangria',
    'ctx_remove_cable': 'Remover cabo da caixa',
    'ctx_edit_cable': 'Editar cabo',
    'ctx_next_box': 'Ir para Próxima Caixa',
    'action_flip': 'Inverter lado',
    'action_rotate': 'Girar',
    'ctx_details': 'Detalhes',
    'toast_select_next_box': 'Selecione a caixa de destino para navegar',
    'error_cable_fully_connected': 'Cabo já conectado em ambas as pontas',
    'select_project_placeholder': 'Selecione o Projeto...',
    'ai_audit': 'Auditoria IA',
    'analyzing': 'Analisando...',
    'tooltip_view': 'Navegação: Clique para editar. Elementos estão travados.',
    'tooltip_move': 'Modo Mover: Arraste CTOs ou POPs para ajustar a posição.',
    'tooltip_otdr': 'Modo OTDR: Clique em um cabo para localizar um evento.',
    'tooltip_add_cto': 'Posicionamento: Clique no mapa para adicionar CTO.',
    'tooltip_add_pop': 'Posicionamento: Clique no mapa para adicionar um POP (Central).',
    'tooltip_add_pole': 'Posicionamento: Clique no mapa para adicionar um poste.',
    'tooltip_draw_cable': 'Desenhando: Clique no mapa ou nó para finalizar o cabo.',
    'tooltip_draw_cable_start': 'Desenhando: Clique no mapa ou Nó para iniciar o cabo.',
    'tooltip_connect': 'Conexão: Clique no cabo para criar ponto de SANGRIA. Arraste até o Nó.',
    'right_click_delete_point': 'Botão direito ou Clique duplo para excluir ponto',
    'ai_report_title': 'Relatório de Engenharia IA',
    'deployment_progress': 'Progresso de Implantação',
    'search_placeholder': 'Buscar CTO, POP ou Coordenadas...',
    'search_no_results': 'Nenhum resultado',

    // New Sidebar Keys
    'sidebar_operation': 'Operação',
    'sidebar_select': 'Selecionar',
    'sidebar_move': 'Mover',
    'sidebar_design': 'Design de Rede',
    'sidebar_add_cto': 'Nova CTO',
    'sidebar_add_pop': 'Novo POP',
    'sidebar_draw_cable': 'Desenhar Cabo',
    'sidebar_draw_cable_desc': 'Clique p/ múltiplos pontos',
    'sidebar_connect_cable': 'Conectar/Editar Cabos',
    'sidebar_connect_cable_desc': 'Ajustar conexões e geometria',
    'registrations': 'Cadastros',
    'manage_networks_desc': 'Gerencie e organize suas redes FTTx.',
    'cables': 'Cabos',
    'search_generic': 'Buscar...',
    'reg_poste': 'Poste',
    'reg_caixa': 'Caixa',
    'reg_cabo': 'Cabo',
    'reg_olt': 'Equipamentos Ativos',
    'reg_clientes': 'Clientes',
    'users': 'Usuários',
    'reg_fusao': 'Conexões',
    'backup': 'Backup',
    'upgrade_now': 'Fazer Upgrade',
    'upgrade_exclusive_msg': 'Este recurso é exclusivo para assinantes. Seus dados estão seguros, mas para exportar é necessário um plano ativo.',
    'manage_subscription': 'Gerenciar Assinatura',
    'trial': 'Teste',
    'expires': 'Expira',
    'days': 'dias',
    'registration_title': 'Cadastro: {name}',
    'registration_placeholder_desc': 'Módulo de cadastro de {name} em desenvolvimento.',
    'module_under_development': 'Este módulo está em desenvolvimento.',
    'description': 'Descrição',
    'reg_splitter': 'Splitter',
    'search_splitters': 'Buscar splitters...',
    'splitter_catalog_desc': 'Gerencie os modelos de splitters no catálogo.',
    'add_splitter': 'Adicionar Splitter',
    'splitter_name': 'Nome do Splitter',
    'splitter_ports': 'Portas',
    'splitter_mode': 'Modo',
    'splitter_type': 'Tipo',
    'splitter_mode_balanced': 'Balanceado',
    'splitter_mode_unbalanced': 'Desbalanceado',
    'splitter_in': 'Entrada',
    'splitter_out': 'Saída',
    'inputs': 'Entradas',
    'outputs': 'Saídas',
    'attenuation': 'Atenuação',
    'attenuation_db': 'Atenuação (dB)',

    'loading': 'Carregando...',
    'loading_diagram': 'Carregando diagrama...',
    'error_saving_splitter': 'Erro ao salvar splitter',
    'sidebar_add_pole': 'Adicionar Poste',
    'sidebar_add_pole_desc': 'Posicionar Manualmente',
    'insertion_options': 'Opções de inserção',
    'olt_catalog_desc': 'Gerencie seus modelos de equipamentos ativos e especificações.',
    'search_olts': 'Buscar equipamentos...',
    'no_olts_found': 'Nenhum equipamento encontrado.',
    'olt_name': 'Modelo',
    'output_power': 'Potência de Saída (dBm)',
    'olt_slots': 'Slots',
    'ports_per_slot': 'Portas/Slot',
    'edit_olt': 'Editar OLT',
    'new_olt': 'Nova OLT',
    'pole_catalog': 'Catálogo de Postes',
    'pole_catalog_desc': 'Gerencie os modelos de postes disponíveis.',
    'new_pole': 'Novo Poste',
    'edit_pole': 'Editar Poste',
    'pole_height': 'Altura (m)',
    'pole_strength': 'Esforço (daN)',
    'pole_shape': 'Formato',
    'concrete': 'Concreto',
    'wood': 'Madeira',
    'metal': 'Metálico',
    'fiber': 'Fibra',
    'shape_circular': 'Circular',
    'shape_duplot': 'Duplo T',
    'shape_square': 'Quadrado',
    'attenuation_port1': 'Atenuação Porta 1 (dB)',
    'attenuation_port2': 'Atenuação Porta 2 (dB)',
    'add_olt': 'Adicionar OLT',
    'reg_active_equipment': 'Equipamentos Ativos',
    'equipment_name': 'Nome do Equipamento',
    'power_consumption': 'Consumo de Energia (W)',
    'olt_output_power_help': 'Classe B+: ~3dBm, C+: ~7dBm',
    'equipment_preview_msg': 'Cria um(a) {type} com {total} portas ({slots} slots × {ports} portas).',
    'error_saving_olt': 'Erro ao salvar equipamento',

    // Toasts
    'toast_imported': 'Importado {ctos} CTOs e {cables} Cabos',
    'toast_cto_added': 'CTO adicionada com sucesso',
    'toast_pop_added': 'POP adicionado com sucesso',
    'toast_cto_splicing_saved': 'Fusões da CTO salvas',
    'toast_pop_saved': 'Configuração do POP salva',
    'toast_cto_deleted': 'CTO removida com sucesso',
    'toast_pole_deleted': 'Poste removido com sucesso',
    'toast_pole_added': 'Poste adicionado com sucesso',
    'toast_cable_updated': 'Cabo atualizado',
    'toast_cable_deleted': 'Cabo deletado',
    'toast_cable_created': 'Cabo criado com sucesso',
    'toast_cable_connected_start': 'Início do cabo conectado a {name}',
    'toast_cable_connected_end': 'Fim do cabo conectado a {name}',
    'toast_cable_split': 'Cabo sangrado e conectado a {name}',
    'toast_cable_anchored_pole': 'Cabo ancorado ao poste {name}',
    'error_cto_duplicate_cable': 'Este cabo já está conectado a esta CTO.',
    'toast_auto_snap_success': 'Auto-conexão/Sangria de {count} pontos em {distance}m.',
    'toast_poles_imported': '{count} postes importados com sucesso!',
    'toast_poles_import_error': 'Erro ao importar postes.',
    'error_cable_endpoint_missing': 'Cabo solto na outra ponta',
    'error_target_not_found': 'Destino não encontrado',
    'toast_select_next_cable': 'Selecione outro cabo para conectar',
    'toast_cable_disconnected': 'Cabo desconectado',
    'import_error': 'Falha ao importar arquivo. Veja o console.',
    'import_no_geo': 'Nenhuma geometria compatível (Pontos ou Linhas) encontrada.',

    // OTDR Messages & Errors
    'otdr_title': 'Calculadora OTDR',
    'otdr_distance_lbl': 'Distância da Medição (m)',
    'otdr_direction': 'Direção',
    'otdr_from_start': 'Do Início (Nó A)',
    'otdr_from_end': 'Do Fim (Nó B)',
    'otdr_locate': 'Localizar Evento',
    'otdr_result': 'Local do Evento',
    'otdr_error_length': 'Distância excede o tamanho do cabo ({length}m)',
    'otdr_trace_start_error': 'Rastreio OTDR: Por favor comece de uma porta de fibra de cabo.',
    'otdr_cable_not_found': 'Erro OTDR: Cabo não encontrado.',
    'otdr_conn_mismatch': 'Erro OTDR: Inconsistência na conectividade do cabo.',
    'otdr_end_open': 'OTDR: Fim da fibra alcançado (Ponta Aberta).',
    'otdr_next_node_error': 'Erro OTDR: Próximo nó não encontrado.',
    'otdr_fiber_end_node': 'OTDR: Fibra termina em {node} (Não fusionada).',
    'otdr_event_equipment': 'OTDR: Evento em {node} (Conexão com Equipamento).',
    'otdr_max_depth': 'OTDR: Profundidade máxima de rastreio atingida.',
    'otdr_success_cable': 'Localizado no cabo {name}',
    'otdr_inside_cto': 'Dentro da CTO {name}',
    'otdr_trace_msg': 'Rastrear a partir da fibra selecionada',
    'otdr_instruction_banner': 'Clique em uma porta de fibra para medir a distância.',
    'otdr_event_tooltip': 'Evento OTDR',

    // CTO Editor Modals
    'select_splitter': 'Selecionar Splitter',
    'select_fusion_type': 'Selecionar Tipo de Fusão',

    // Modal de Potência Óptica
    'optical_budget': 'Orçamento Óptico',
    'optical_path_for': 'Caminho óptico para',
    'no_signal': 'Sem Sinal (Desconectado)',
    'final_power': 'Potência Final',
    'status_ok': 'OK (Ideal)',
    'status_marginal': 'Marginal (Alerta)',
    'status_fail': 'Falha (Crítico)',
    'origin_olt': 'Origem (OLT)',
    'output_power_short': 'Potência de Saída',
    'total_loss': 'Perda Total',
    'path_elements': 'Elementos no caminho',
    'path_details': 'Detalhes do Percurso',
    'type_CABLE': 'Cabo',
    'type_SPLITTER': 'Splitter',
    'type_FUSION': 'Fusão',
    'type_CONNECTOR': 'Conector / DIO',
    'type_OLT': 'OLT',

    // Common
    'save': 'Salvar',
    'cancel': 'Cancelar',
    'edit': 'Editar',
    'delete': 'Excluir',
    'confirm': 'Confirmar',
    'connect': 'Conectar',
    'edit_node_short': 'Editar',
    'move_node_short': 'Mover',
    'delete_node_short': 'Excluir',

    'name': 'Nome',
    'type': 'Tipo',
    'pole_label': 'Poste',
    'color': 'Cor',
    'id': 'ID',
    'manage_splicing': 'Gerenciar fusões',
    'manage_pop': 'Gerenciar rack e patching',
    'unsaved_changes': 'Alterações não salvas',
    'unsaved_changes_msg': 'Você tem alterações não salvas. Deseja salvá-las antes de sair?',
    'discard': 'Descartar',
    'save_and_close': 'Salvar e sair',
    'save_or_done': 'Salvar / sair',
    'clear_connections_confirm': 'Tem certeza que deseja limpar todas as conexões? Isso não pode ser desfeito.',
    'changes_saved': 'Alterações salvas com sucesso',
    'position_saved': 'Posição salva com sucesso!',
    'save_position': 'Salvar posição',
    'moving_node': 'Movendo elemento...',
    'editing_cable': 'Editando cabo...',
    'connecting_cable': 'Conectando cabos...',
    'finish': 'Concluir',
    'finish_cable': 'Finalizar cabo',
    'connection_cancelled': 'Conexão cancelada',
    'meters': 'metros',
    'saved': 'Salvo',
    'done': 'Concluir',
    'clear_all': 'Limpar tudo',
    'confirm_delete': 'Tem certeza?',
    'confirm_delete_equip_msg': 'Tem certeza que deseja deletar {name}?',
    'delete_warning_msg': 'Aviso: Todas as conexões associadas a este {type} serão removidas permanentemente.',

    // Statuses
    'status_PLANNED': 'Em projeto',
    'status_NOT_DEPLOYED': 'Não implantado',
    'status_DEPLOYED': 'Implantado',
    'status_CERTIFIED': 'Certificado',
    'status_ANALYSING': 'Em análise',
    'status_LICENSED': 'Licenciado',

    // Pole Details
    'pole_properties': 'Propriedades do poste',
    'select_pole': 'Selecionar Poste',
    'search_pole': 'Buscar modelo de poste...',
    'pole_type': 'Tipo de poste',
    'selection_pole_type': 'Tipo de poste',
    'pole_height_placeholder': 'Ex: 10',
    'delete_pole_btn': 'Deletar poste',
    'confirm_delete_pole_msg': 'Tem certeza que deseja deletar {name}?',
    'confirm_delete_pole_confirm': 'Deseja excluir este poste?',

    // CTO/POP Details
    'edit_cto': 'Editar CTO',
    'edit_pop': 'Editar POP',
    'cto_info': 'Informações da CTO',
    'pop_info': 'Informações do POP',

    'connections': 'Conexões',
    'spliced': 'Fusões',
    'patched': 'Manobras',

    'fusion_tool_active': 'Modo Fusão: Clique para adicionar fusão',
    'splitters': 'Splitters',
    'equipment': 'Equipamentos',
    'backbone_cables': 'Cabos Backbone',
    'confirm_delete_cto_msg': 'Confirmar deleção de {name}? Todos os cabos conectados serão removidos.',
    'confirm_delete_pop_msg': 'Confirmar deleção do POP {name}? Isso removerá racks, equipamentos e cabos.',
    'delete_cto_btn': 'Deletar CTO',
    'delete_pop_btn': 'Deletar POP',

    // Cable Editor
    'edit_cable': 'Editar cabo',
    'cable_name': 'Nome do cabo',
    'fiber_count': 'Qtd. de fibras',
    'unit_fibers': 'FIBRAS',
    'unit_fiber_label': 'Fibra {n}',
    'use_catalog_model': 'Usar modelo do catálogo',
    'loading_catalog': 'Carregando catálogo...',
    'select_model': '-- Selecione um modelo --',
    'loose_tubes': 'Tubos loose',
    'tube': 'Tubo',
    'technical_reserve': 'Reserva técnica',
    'geometric_length': 'Comprimento geométrico',
    'estimated_length': 'Comprimento est.',
    'toggle_reserve_label': 'Mostrar reserva técnica',
    'position_reserve_label': 'Posicionar reserva',
    'hide_reserve_label': 'Ocultar reserva técnica',
    'tooltip_position_reserve': 'Clique no mapa para posicionar a reserva técnica',
    'toast_reserve_positioned': 'Reserva posicionada com sucesso',
    'map_color': 'Cor no mapa',
    'catalog_defined': 'Definido no catálogo',
    'color_selection_info': 'Cor definida pelo catálogo de acordo com o status.',
    'disabled': 'Desativado',
    'confirm_delete_cable_msg': 'Confirmar deleção de {name}? Isso removerá as fusões associadas.',
    'connect_cable': 'Conectar cabo',
    'connect_to_box': 'Conectar à Caixa',
    'delete_cable': 'Excluir cabo',
    'properties': 'Propriedades',
    'color_standard': 'Padrão de cores',
    'standard_abnt': 'ABNT (Brasil)',
    'standard_eia': 'EIA-598-A (Intl)',
    'fiber_color_standard': 'Padrão de Cores',
    'toast_mode_move_node': 'Modo mover ativado',

    'project_manager': 'Gerenciador de projetos',
    'create_project': 'Criar projeto',
    'new_project_placeholder': 'Nome do Projeto (ex: Expansão Centro)',
    'import_kmz_title': 'Importar KMZ/KML para Projeto Atual',
    'import_kmz_label': 'Importar KMZ/KML',
    'import_kmz_desc': 'Clique para enviar arquivo .kmz ou .kml',
    'processing': 'Processando...',
    'your_projects': 'Seus Projetos',
    'load_project': 'Carregar',
    'delete_last_project_error': 'Não é possível deletar o último projeto.',
    'confirm_delete_project': 'Deseja excluir este projeto? Esta ação não pode ser desfeita.',
    'active': 'Ativo',
    'items_count': 'Itens: {ceos} CEOs, {ctos} CTOs, {cables} Cabos',
    'search_location': 'Localização Inicial',
    'search_location_placeholder': 'Pesquise cidade ou endereço...',
    'searching_location': 'Buscando...',
    'no_location_results': 'Local não encontrado',

    'create_project_modal_title': 'Criar Novo Projeto',
    'search_existing_customer': 'Buscar cliente cadastrado...',
    'no_customers_found': 'Nenhum cliente cadastrado.',
    'locate_on_map': 'Localizar no mapa',
    'edit_project': 'Editar Projeto',
    'map_instruction': 'Arraste o mapa ou clique para definir o centro do projeto.',
    'confirm_create': 'Criar Projeto',
    'snap_distance_lbl': 'Distância de Imã (metros)',
    'snap_distance_help': 'Distância máxima para um cabo "grudar" automaticamente em uma caixa (CTO/POP) ao arrastar.',

    // CTO Internal Editor
    'splicing_title': '{name}',
    'dio_splicing_title': 'Fusão DIO: {name}',
    'splicing_help': 'Role para Zoom. Arraste fundo para mover. Duplo-clique remove pontos.',
    'add_fusion': 'Fusão',
    'auto_splice': 'Auto Passante',
    'auto_splice_help': 'Fusão automatizada de fibras',
    'auto_splice_desc': 'Selecione dois cabos para conectar todas as fibras sequencialmente (1 com 1, 2 com 2...).',
    'auto_splice_compatible': 'A quantidade de fibras deve ser compatível para melhores resultados.',
    'select_cable': 'Selecionar Cabo...',
    'rotate_mode': 'Modo de Rotação',
    'delete_mode': 'Modo de Exclusão',
    'otdr_trace_tool': 'Traço OTDR',
    'snap_grid': 'Ajustar à Grade',
    'reset_connections': 'Resetar Conexões',
    'drop_to_connect': 'Solte na porta para conectar, ou no fundo para desconectar.',
    'moving_point': 'Movendo ponto de controle...',
    'panning': 'Movendo tela',
    'general_help': 'Arraste portas para conectar. Clique nas linhas para criar curvas. Duplo-clique para remover.',
    'rename_fusion': 'Renomear Ponto de Fusão:',
    'export_pdf': 'Exportar PDF',
    'generating_pdf': 'Gerando...',
    'tool_vfl': 'VFL (Caneta Óptica)',
    'vfl_active_msg': 'VFL Ativo: Clique em qualquer porta para injetar a luz.',

    'vfl_source_label': 'Fonte: {name}',
    'turn_off': 'Desligar',
    'source_cable': 'Cabo Origem',
    'target_cable': 'Cabo Destino',
    'perform_splice': 'Fusionar Todos',
    'splice_success': 'Sucesso ao fusionar {count} fibras.',
    'smart_align': 'Alinhamento Inteligente',

    // DIO Editor Strings
    'link_cables': 'Vincular Cabos',
    'linked_pole': 'Poste Vinculado',
    'unlinked': 'Sem vínculo',
    'linked_cables': 'Cabos Vinculados',
    'no_cables_linked': 'Nenhum Cabo Vinculado',
    'link_cables_help': 'Você pode vincular cabos a este DIO usando o botão acima.',
    'connect_fiber_tray': 'Conectar Fibra à Bandeja DIO',
    'connected_to_port': 'Atualmente conectado à Porta {port}',
    'select_tray_port_help': 'Selecione uma porta da bandeja abaixo para fusionar esta fibra.',
    'green_light_help': 'Luzes verdes indicam sinal OLT ativo fluindo para o cabo.',
    'select_target_port_dio': 'Selecione uma Porta de Destino em {name}',
    'currently_connected': 'Atualmente Conectado',
    'port_occupied_splice': 'Porta ocupada por outra fusão',
    'port_has_patch_cord': 'Porta possui patch cord (Fusão permitida)',
    'port_available': 'Disponível',
    'linked_to_dio': 'Vinculado a {name}',
    'legend_active_signal': 'Sinal Ativo',
    'legend_vfl_source': 'Fonte VFL',
    'unit_meters': 'METROS',
    'click_to_manage': 'Clique para Gerenciar',
    'click_to_connect': 'Clique para Conectar',
    'splice_trays': 'Bandejas de Fusão',

    // Box Catalog
    'box_catalog': 'Catálogo de Caixas',
    'box_catalog_desc': 'Gerencie os modelos de caixas (CTO/CEO) disponíveis.',
    'confirm_delete_title': 'Confirmar Exclusão',
    'confirm_delete_message': 'Tem certeza que deseja excluir este item? Esta ação não pode ser desfeita.',
    'no_results': 'Nenhuma caixa encontrada',
    'name_placeholder': 'Ex: CTO-PRECON',
    'brand_placeholder': 'Ex: Furukawa, Prysmian...',
    'model_placeholder': 'Ex: AS-80, Drop Flat...',
    'equipment_name_placeholder': 'Ex: Huawei MA5608T, Cisco 2960...',
    'box_model': 'Modelo de Caixa',
    'select_box_model': 'Selecione Modelo...',
    'reserve_loop_length': 'Reserva Técnica',
    'reserve': 'Reserva',
    'brand': 'Marca',
    'model': 'Modelo',
    'ident_color': 'Cor de Identificação',
    'type_cto_termination': 'CTO (Terminação)',
    'type_ceo_splice': 'CEO (Emenda)',
    'edit_box': 'Editar Caixa',
    'new_box': 'Nova Caixa',
    'search_placeholder_box': 'Buscar por nome, marca ou modelo...',
    'details_placeholder': 'Detalhes adicionais ou especificações técnicas...',
    'fusion_catalog_desc': 'Gerencie seus tipos de fusão padrão e valores de atenuação.',
    'new_fusion': 'Nova Fusão',
    'edit_fusion': 'Editar Fusão',

    'bm_cancel': 'Cancelar',

    // Cable Catalog
    'cable_catalog': 'Catálogo de Cabos',
    'cable_catalog_desc': 'Gerencie os modelos de cabos disponíveis para projetos.',
    'new_cable': 'Novo Cabo',
    'save_cable': 'Salvar Cabo',
    'search_placeholder_cable': 'Buscar por código ou marca...',
    'error_save_cable': 'Erro ao salvar cabo',
    'name_required': 'Código é obrigatório',
    'allow_custom_connections': 'Permitir conexão de clientes',


    // POP Editor
    'pop_editor_title': 'Gerenciamento POP: {name}',
    'add_dio': 'Adicionar DIO',
    'add_active_equipment': 'Adicionar Ativo',
    'olt_ports': 'Portas PON',
    'active_ports': 'Portas',
    'dio_ports': 'Portas',
    'rack_view': 'Visão do Rack',

    // OLT/DIO Modal
    'modal_add_olt_title': 'Adicionar Equipamento Ativo',
    'modal_edit_olt_title': 'Editar Equipamento Ativo',
    'modal_add_dio_title': 'Adicionar Equipamento Passivo (DIO)',
    'modal_edit_dio_title': 'Editar DIO',
    'equipment_type': 'Tipo de Equipamento',
    'type_olt': 'OLT (GPON)',
    'type_switch': 'Switch',
    'type_router': 'Roteador',
    'type_server': 'Servidor',
    'type_other': 'Outro',
    'custom_configuration': 'Configuração Personalizada',
    'catalog_label': 'Catálogo',
    'chassis_config': 'Configuração do Chassi',
    'total_slots': 'Total de Slots',
    'preview': 'Pré-visualização',
    'olt_preview_msg': 'Isso criará uma OLT de {total} portas ({slots} slots × {ports} portas).',
    'olt_config_locked_msg': 'Capacidade do chassi gerenciada via Catálogo.',
    'create_device': 'Criar Dispositivo',
    'specifications': 'Especificações',
    'dio_preview_msg': 'Cria um DIO de rack com capacidade de {ports} fusões organizado em {trays} bandejas.',
    'ports_label': 'Portas',
    'capacity_label': 'Capacidade',
    'dio_capacity_warning': 'Reduzir a capacidade apagará permanentemente as conexões nas portas removidas.',
    'n_ports': '{n} Portas',
    'manage_slots': 'Gerenciar Placas',
    'slot_active': 'Ativo',
    'slot_empty': 'Vazio',
    'port_count': 'Portas',
    'add_card': 'Adicionar Placa',
    'slot_label': 'Slot {n}',
    'type_change_warning': 'Alterar o tipo do equipamento pode redefinir a estrutura de portas e remover conexões existentes.',
    'type_locked': 'Tipo de equipamento bloqueado para manter integridade da estrutura.',
    'connection_slot_port': 'Conexão para Slot/Porta',
    'select_dio_port': 'Selecione a Porta do DIO',
    'connected': 'Conectado',
    'not_connected': 'Não Conectado',
    'disconnect': 'Desconectar',
    'save_changes': 'Salvar Alterações',

    // Users Module
    'users': 'Usuários',
    'users_manage_desc': 'Gerencie membros da equipe e seus cargos.',
    'add_user': 'Adicionar Usuário',
    'username': 'Usuário',
    'email': 'E-mail',
    'role': 'Cargo',
    'created_at': 'Criado em',
    'actions': 'Ações',
    'no_users_found': 'Nenhum usuário encontrado.',
    'role_member': 'Membro',
    'role_admin': 'Admin',
    'role_owner': 'Dono',
    'password': 'Senha',
    'edit_user': 'Editar Usuário',
    'update': 'Atualizar',
    'confirm_delete_user_msg': 'Tem certeza que deseja deletar o usuário {username} ({email})?',
    'create': 'Criar',

    // User Management Errors
    'error_username_taken': 'Este nome de usuário ou e-mail já está em uso.',
    'error_email_taken': 'Este e-mail já está em uso.',
    'error_password_length': 'A senha deve ter pelo menos 6 caracteres.',
    'error_cannot_delete_self': 'Você não pode deletar sua própria conta.',
    'error_generic': 'Ocorreu um erro inesperado.',
    'error_create_user': 'Falha ao criar usuário.',
    'error_delete_user': 'Falha ao deletar usuário.',
    'error_email_required': 'O e-mail é obrigatório.',
    'error_permission_denied': 'Acesso negado: você não tem permissão para realizar esta ação.',

    // Map Layers
    'map_street': 'MAP',
    'map_satellite': 'Satélite',
    'map_layers': 'Camadas',
    'layer_cables': 'Cabos',
    'layer_ctos': 'CTOs',
    'layer_pops': 'POPs',

    // Backup
    'backup_title': 'Gerenciador de Backup',
    'backup_desc': 'Gerencie os backups do sistema. Backups diários são executados automaticamente às 02:00 AM.',
    'create_backup': 'Criar Backup',
    'backup_filename': 'Nome do Arquivo',
    'backup_date': 'Data',
    'backup_size': 'Tamanho',
    'download': 'Baixar',
    'confirm_delete_backup': 'Tem certeza que deseja deletar este backup?',
    'backup_success': 'Backup criado com sucesso',
    'backup_created_at': 'Criado em',
    'backup_manual': 'Manual',

    'backup_auto': 'Automático',
    'no_backups': 'Nenhum backup encontrado.',
    'restore': 'Restaurar',
    'upload_restore': 'Enviar & Restaurar',
    'restore_confirm': 'AVISO: Isso irá apagar TODOS os dados de rede atuais (CTOs, Cabos, POPs, Projetos) e substituí-los pelo backup. Isso não pode ser desfeito. Tem certeza?',
    'restore_success': 'Sistema restaurado com sucesso. Recarregando...',
    'apply': 'Aplicar',
    'maximize': 'Maximizar',
    'mode_ruler': 'Régua',
    'tooltip_ruler': 'Régua: Clique no mapa para medir a distância entre pontos.',
    'ruler_clear': 'Limpar Régua',
    'ruler_total': 'Distância Total',
    'admin_col_phone': 'Telefone',
    'admin_col_infrastructure': 'Infraestrutura',
    'admin_col_created': 'Criado em',
    'admin_col_last_access': 'Último Acesso',
    'admin_never': 'Nunca',
    'admin_no_phone': 'Sem telefone',

    // Report / Network Analysis
    'report_title': 'Relatório do Projeto',
    'report_analyze': 'Análise de Rede',
    'report_summary': 'Resumo',
    'report_infrastructure': 'Infraestrutura',
    'report_cables': 'Cabos e Fibras',
    'report_qty': 'Qtd',
    'report_total_ctos': 'Total de CTOs',
    'report_total_ceos': 'Total de CEOs (Emenda)',
    'report_total_pops': 'Total de POPs (Centrais)',
    'report_total_poles': 'Total de Postes',
    'report_cable_type': 'Tipo de Fibra',
    'report_cable_count_active': 'Cabos Ativos',
    'report_total_meters': 'Metragem Total',
    'report_total_meters_active': 'Total Implantado (m)',
    'report_total_meters_planned': 'Total Projetado (m)',
    'report_no_data': 'Nenhum dado disponível para análise.',
    'report_export_csv': 'Exportar CSV',
    'report_estimated': 'Estimado',
    'email_admin_new_client_subject': 'Novo Cliente Cadastrado: {company}',
    'email_admin_new_client_body': 'Um novo cliente se cadastrou no sistema.<br><br><b>Detalhes:</b><br><ul><li><b>Usuário:</b> {username}</li><li><b>Empresa:</b> {company}</li><li><b>E-mail:</b> {email}</li><li><b>Telefone:</b> {phone}</li><li><b>Plano:</b> {plan}</li><li><b>Origem:</b> {source}</li></ul>',

    // Missing Keys
    'draw_drop': 'Desenhar Cabo',
    'sidebar_add_customer': 'Adicionar Cliente',
    'confirm_disconnect': 'Tem certeza que deseja desconectar este cliente? Isso removerá o cabo e a conexão.',
    'disconnect': 'Desconectar',

    // Clientes
    'layer_customers': 'Clientes',
    'customer_title': 'Clientes',
    'add_customer': 'Adicionar Cliente',
    'customer_name': 'Nome',
    'customer_doc': 'Documento (CPF/CNPJ)',
    'customer_phone': 'Telefone',
    'customer_address': 'Endereço',
    'customer_connection': 'Conexão',
    'select_cto': 'Selecionar CTO',
    'select_port': 'Selecionar Porta',
    'customer_status_title': 'Status',
    'customer_status_active': 'Ativo',
    'customer_status_inactive': 'Inativo',
    'customer_status_planned': 'Em Projeto',
    'no_ctos_near': 'Nenhuma CTO próxima encontrada.',
    'port_free': 'Livre',
    'port_occupied': 'Ocupada',
    'save_customer': 'Salvar Cliente',
    'saving': 'Salvando...',
    'customer_port_tooltip': 'Cliente: {name}',
    'port_label': 'Porta {number}',
    'nearest_cto': 'CTO Mais Próxima',
    'view_diagram': 'Ver Diagrama',
    'delete_customer': 'Excluir Cliente',
    'confirm_delete_customer': 'Tem certeza que deseja excluir este cliente? Isso removerá suas conexões.',
    'draw_customer_drop': 'Desenhar Cabo',
    'error_port_occupied': 'Porta Ocupada',
    'error_port_occupied_desc': 'Esta porta já está em uso pelo cliente {name}.',
    'box_full': 'Caixa Cheia',
    'connection_failed_title': 'Falha na Conexão',
    'connection_failed_msg': 'Não foi possível salvar a conexão.',
    'port_status_occupied': 'Ocupada ({name})',
    'port_status_free': 'Livre',
    'customer_modal_title': 'Adicionar/Editar Cliente',
    'customer_data': 'Dados do Cliente',
    'connected_cto': 'CTO Conectada',
    'change': 'Alterar',
    'no_splitters_in_cto': 'Nenhum splitter nesta CTO',
    'select_splitter': 'Selecionar Splitter',
    'port_occupied_by': 'Ocupada por {name}',
    'draw_customer_drop_desc': 'Clique para desenhar o cabo drop do cliente até a CTO.',
    'onu_data_section': 'Dados da ONU / Conexão',
    'onu_serial': 'Serial da ONU',
    'pppoe_user': 'Usuário PPPoE',
    'onu_mac': 'MAC Address',
    'cancel': 'Cancelar',
    'search_existing_customer': 'Buscar cliente existente...',
    'no_customers_found': 'Nenhum cliente encontrado.',
    'onu_power': 'Potência da ONU (dBm)',
    'drop_length': 'Comprimento do Drop',
    'meters_abbrev': 'm',
    'draw_drop_instruction': 'Clique no mapa para traçar a rota',
    'select_cto_drop': 'Clique na CTO para conectar',
    'right_click_cancel': 'Botão direito para cancelar',
    'connect_customer_title': 'Conectar Cliente',
    'connect_customer_desc': 'Selecione uma porta para finalizar a conexão',
    'target_cto': 'CTO Alvo',
    'no_splitters_found_error': 'Nenhum splitter encontrado. É necessário instalar um splitter para conectar.',
    'ports_total': '{count} Portas no Total',
    'select_free_port': 'Selecione uma porta livre para continuar.',
    'selected_port_info': 'Selecionada: Porta {port}',
    'reposition_customer': 'Mover Cliente',
    'reposition_customer_instruction': 'Clique no novo local para o cliente',
    'repositioning': 'Movendo...',

    // Catálogos e Cadastros
    'add_new': 'Adicionar Novo',

    // Cadastro de Clientes
    'manage_customers_desc': 'Gerencie a base de clientes e conexões.',
    'customer_status_title': 'Status',
    'customer_status_active': 'Ativo',
    'customer_status_inactive': 'Inativo',
    'customer_status_planned': 'Planejado',
    'confirm_delete_customer': 'Tem certeza que deseja excluir este cliente?',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('ftth_language');
      return (saved as Language) || 'pt';
    }
    return 'pt';
  });

  React.useEffect(() => {
    localStorage.setItem('ftth_language', language);
  }, [language]);

  const t = (key: string, params?: Record<string, string | number>) => {
    let text = translations[language][key as keyof typeof translations['en']] || key;

    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
